name: ANUPQ
version: 3.2.4
date: 2022-02-22
description: |
    ANU p-Quotient

authors:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Eamonn O'Brien
      url: https://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "autpgrp"
      version: ">=1.5"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/anupq/
readme: README
packageinfo: https://gap-packages.github.io/anupq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/anupq/releases/download/v3.2.4/anupq-3.2.4.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/anupq/releases/download/v3.2.4/anupq-3.2.4.tar.bz2

abstract: |
    The <span class="pkgname">ANUPQ</span> package provides an interactive    interface to the p-quotient, p-group generation and standard presentation    algorithms of the ANU pq C program.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    p-quotient, p-group generation, descendant, standard presentation.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GNOH22</span>]   <b class='BibAuthor'>Gamble, G., Nickel, W., O'Brien, E. and Horn, M.</b>,
     <i class='BibTitle'>ANUPQ, ANU p-Quotient,
             Version 3.2.4</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/anupq/">https://gap-packages.github.io/anupq/</a></span>.
    </p>
    

bibtex: |
    @misc{ ANUPQ3.2.4,
      author =           {Gamble, G. and Nickel, W. and O'Brien, E. and Horn, M.},
      title =            {{ANUPQ}, ANU p-Quotient, {V}ersion 3.2.4},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/anupq/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{anupq/}}},
      keywords =         {p-quotient;  p-group  generation; descendant; standard
                          presentation},
      printedkey =       {GNOH22}
    }

