name: ANUPQ
version: "3.3.2"
license: "Artistic-2.0"
date: 2025-08-28
description: |
    ANU p-Quotient

authors:
    - name: Greg Gamble
      url: mailto:Greg.Gamble@uwa.edu.au
    - name: Werner Nickel
    - name: Eamonn O'Brien
      url: https://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "autpgrp"
      version: ">=1.5"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/anupq/
readme: README.md
packageinfo: https://gap-packages.github.io/anupq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/anupq/releases/download/v3.3.2/anupq-3.3.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/anupq/releases/download/v3.3.2/anupq-3.3.2.tar.bz2

abstract: |
    The <span class="pkgname">ANUPQ</span> package provides an interactive    interface to the p-quotient, p-group generation and standard presentation    algorithms of the ANU pq C program.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    p-quotient, p-group generation, descendant, standard presentation.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GNOH25</span>]   <b class='BibAuthor'>Gamble, G., Nickel, W., O'Brien, E. and Horn, M.</b>,
     <i class='BibTitle'>ANUPQ, ANU p-Quotient,
             Version 3.3.2</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/anupq/">https://gap-packages.github.io/anupq/</a></span>.
    </p>
    

bibtex: |
    @misc{ ANUPQ,
      author =           {Gamble, G. and Nickel, W. and O'Brien, E. and Horn, M.},
      title =            {{ANUPQ},      {ANU     p\texttt{\symbol{45}}Quotient},
                          {V}ersion 3.3.2},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/anupq/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{anupq/}}},
      keywords =         {p\texttt{\symbol{45}}quotient;
                          p\texttt{\symbol{45}}group   generation;   descendant;
                          standard presentation},
      printedkey =       {GNOH25}
    }

