#!/bin/sh
#########################################################################
##
#W  make_doc     make ANUPQ Share Package documentation       Greg Gamble
##
#H  $Id$
##
##  This shell script uses TeX, BibTeX and MakeIndex to  build  the  .dvi
##  PostScript (commented  out) and HTML (provided  you  have   tth   and
##  etc/convert.pl) documentation for the ANUPQ Share Package.
##

echo "TeXing documentation"
# TeX the manual and build its bibliography
tex manual;bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual; ../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
# Create the PostScript version (uncomment next line, if needed)
#dvips -D300 manual -o

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -t -c -n ANUPQ . ../htm

#########################################################################
##
#E
