# Generated by tst/make_example_tests.g from examples/11gp-SP-a-i
gap> START_TEST( "11gp-SP-a-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "R", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b"); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> R := [a^11, b^11/PqLeftNormComm([b, a, a])^2, 
>       PqLeftNormComm([b, a, b, b, b, b])];;
gap> procId := PqStart(F/R : Prime := 11);;
gap> PqSetOutputLevel(procId, 0);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 3);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,0,1],
>                                     [0,1,0,0,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [0,1,0,1,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [0,1,0,0,1]],
> 
>                                    [[1,0,0,0,0],
>                                     [3,1,0,0,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [9,3,0,0,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [6,6,0,0,0]],
> 
>                                    [[10,0,0,0,0],
>                                     [2,1,0,0,0]] ]
> 
>                          : # options
>                            ClassBound := 19,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-SP-a-i.tst", 1 );
