# Generated by tst/make_example_tests.g from examples/11gp-PG-i
gap> START_TEST( "11gp-PG-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c");
<free group on the generators [ a, b, c ]>
gap> procId := PqStart(F : Prime := 11);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-11 central series for [grp]
#I  Group: [grp] to lower exponent-11 central class 1 has order 11^3
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-11 central class 2 has order 11^9
gap> PqPGSupplyAutomorphisms(procId, [ [[ 2, 0, 0],
>                                    [ 0, 1, 0],
>                                    [ 0, 0, 1]],
> 
>                                   [[10, 0, 1],
>                                    [10, 0, 0],
>                                    [ 0,10, 0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 2,
>                                   CapableDescendants,
>                                   StepSize := 1,
>                                   RankInitialSegmentSubgroups := 3);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 11^3
#I  Nuclear rank: 6
#I  11-multiplicator rank: 6
#I  # of immediate descendants of order 11^4 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
2

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-PG-i.tst", 1 );
