# Generated by tst/make_example_tests.g from examples/11gp-a-Rel-i
gap> START_TEST( "11gp-a-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["[b, a, a, b, b]^11", "[a, b, b, a, b, b]^11", "(a * b)^11"];
[ "[b, a, a, b, b]^11", "[a, b, b, a, b, b]^11", "(a * b)^11" ]
gap> procId := PqStart(F : Prime := 11, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 8, 
>                           OutputLevel := 1);;
#I  Lower exponent-11 central series for [grp]
#I  Group: [grp] to lower exponent-11 central class 1 has order 11^2
#I  Group: [grp] to lower exponent-11 central class 2 has order 11^4
#I  Group: [grp] to lower exponent-11 central class 3 has order 11^7
#I  Group: [grp] to lower exponent-11 central class 4 has order 11^11
#I  Group: [grp] to lower exponent-11 central class 5 has order 11^18
#I  Group: [grp] to lower exponent-11 central class 6 has order 11^28
#I  Group: [grp] to lower exponent-11 central class 7 has order 11^47
#I  Group: [grp] to lower exponent-11 central class 8 has order 11^78
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-a-Rel-i.tst", 1 );
