# Generated by tst/make_example_tests.g from examples/11gp-SP-a-Rel-1-i
gap> START_TEST( "11gp-SP-a-Rel-1-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^11", "b^11*[b, a, a]^-2", "[b, a, b, b, b, b]"];
[ "a^11", "b^11*[b, a, a]^-2", "[b, a, b, b, b, b]" ]
gap> procId := PqStart(F : Prime := 11, Relators := rels);;
gap> PqSetOutputLevel(procId, 0);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[1,0],
>                                     [0,1]],
> 
>                                    [[1,0],
>                                     [0,1]],
> 
>                                    [[1,0],
>                                     [0,1]],
> 
>                                    [[1,0],
>                                     [3,1]],
> 
>                                    [[1,0],
>                                     [9,3]],
> 
>                                    [[1,0],
>                                     [6,6]],
> 
>                                    [[10,0],
>                                     [2,1]] ]
> 
>                          : # options
>                            ClassBound := 19,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-SP-a-Rel-1-i.tst", 1 );
