# Generated by tst/make_example_tests.g from examples/11gp-SP-b-i
gap> START_TEST( "11gp-SP-b-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "c", "R", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c"); a := F.1; b := F.2; c := F.3;
<free group on the generators [ a, b, c ]>
a
b
c
gap> R := [a^11, b^11, c^11, PqLeftNormComm([b, a, a, a, b, a]),
>       Comm(c, a), Comm(c, b), PqLeftNormComm([b, a, b])];;
gap> procId := PqStart(F/R : Prime := 11);;
gap> PqSetOutputLevel(procId, 0);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 3);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,0,0],
>                                     [0,1,0,0,1],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,1]],
> 
>                                    [[1,0,9,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,7,8,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[10,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[2,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,8,0,0],
>                                     [0,1,3,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,9,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,3,0,0]],
> 
>                                    [[1,0,2,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,10,0,0]],
> 
>                                    [[1,9,10,0,0],
>                                     [0,3,7,0,0],
>                                     [0,0,6,0,0]],
> 
>                                    [[1,5,9,0,0],
>                                     [0,7,4,0,0],
>                                     [0,0,10,0,0]]]
> 
>                          : # options
>                            ClassBound := 8,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-SP-b-i.tst", 1 );
