# Generated by tst/make_example_tests.g from examples/11gp-3-Engel-Id-i
gap> START_TEST( "11gp-3-Engel-Id-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "G", "f", "procId", "Q" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b"); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> G := F/[ a^11, b^11 ];
<fp group on the generators [ a, b ]>
gap> # All word pairs u, v in the pc generators of the 11-quotient Q of G 
gap> # must satisfy the Engel identity: [u, v, v, v] = 1.
gap> f := function(u, v) return PqLeftNormComm( [u, v, v, v] ); end;
function( u, v ) ... end
gap> procId := PqStart( G : Prime := 11 );;
gap> PqPcPresentation( procId : ClassBound := 1);;
gap> PqEvaluateIdentities( procId : Identities := [f] );;
#I  Class 1 with 2 generators.
gap> for c in [2 .. 4] do
>   PqNextClass( procId : Identities := [] ); #reset `Identities' option
>   PqEvaluateIdentities( procId : Identities := [f] );
> od;
#I  Class 2 with 3 generators.
#I  Class 3 with 5 generators.
#I  Class 3 with 5 generators.
gap> Q := PqCurrentGroup( procId );
<pc group of size 161051 with 5 generators>
gap> # We do a ``sample'' check that pairs of elements of Q do satisfy
gap> # the given identity:
gap> f( Random(Q), Random(Q) );
<identity> of ...
gap> f( Q.1, Q.2 );
<identity> of ...

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-3-Engel-Id-i.tst", 1 );
