# Generated by tst/make_example_tests.g from examples/11gp-SP-b-Rel-i
gap> START_TEST( "11gp-SP-b-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c");
<free group on the generators [ a, b, c ]>
gap> rels := ["a^11", "b^11", "c^11", "[b, a, a, a, b, a]", 
>          "[c, a]", "[c, b]", "[b, a, b]"];
[ "a^11", "b^11", "c^11", "[b, a, a, a, b, a]", "[c, a]", "[c, b]", 
  "[b, a, b]" ]
gap> procId := PqStart(F : Prime := 11, Relators := rels);;
gap> PqSetOutputLevel(procId, 0);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 3);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,0,0],
>                                     [0,1,0,0,1],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,1]],
> 
>                                    [[1,0,9,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,7,8,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[10,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[2,0,0,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,8,0,0],
>                                     [0,1,3,0,0],
>                                     [0,0,1,0,0]],
> 
>                                    [[1,0,9,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,3,0,0]],
> 
>                                    [[1,0,2,0,0],
>                                     [0,1,0,0,0],
>                                     [0,0,10,0,0]],
> 
>                                    [[1,9,10,0,0],
>                                     [0,3,7,0,0],
>                                     [0,0,6,0,0]],
> 
>                                    [[1,5,9,0,0],
>                                     [0,7,4,0,0],
>                                     [0,0,10,0,0]]]
> 
>                          : # options
>                            ClassBound := 8,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "11gp-SP-b-Rel-i.tst", 1 );
