# Generated by tst/make_example_tests.g from examples/2gp-SP-d-Rel-i
gap> START_TEST( "2gp-SP-d-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> rels := ["b^4", "b^2 * [b, a, a]^-1", "d^16", "a^16 * (c * d)^-1",
>          "b^8 * (d * c^4)^-1", "b * (a^2 * b^-1 * a^2)^-1"];
[ "b^4", "b^2 * [b, a, a]^-1", "d^16", "a^16 * (c * d)^-1", 
  "b^8 * (d * c^4)^-1", "b * (a^2 * b^-1 * a^2)^-1" ]
gap> procId := PqStart(F : Prime := 2, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[0,1],
>                                     [1,1]],
> 
>                                    [[0,1],
>                                     [1,0]] ]
> 
>                          : # options
>                            ClassBound := 10,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-SP-d-Rel-i.tst", 1 );
