# Generated by tst/make_example_tests.g from examples/2gp-PG-e4-i
gap> START_TEST( "2gp-PG-e4-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 2);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
gap> PqPGSupplyAutomorphisms(procId, [ [[0,1],
>                                    [1,1]],
> 
>                                   [[0,1],
>                                    [1,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 12,
>                                   PcgsAutomorphisms,
>                                   Exponent := 4);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 2^2
#I  Nuclear rank: 3
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^3 is 3
#I  # of immediate descendants of order 2^4 is 3
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 2^5 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1
#I  Order: 2^3
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #2;1
#I  Order: 2^3
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #3;1
#I  Order: 2^3
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2
#I  Order: 2^4
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #4;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2
#I  Order: 2^4
#I  Nuclear rank: 1
#I  2-multiplicator rank: 2
#I  # of immediate descendants of order 2^5 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2
#I  Order: 2^4
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #6;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 2
#I  # of immediate descendants of order 2^6 is 1
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 2^7 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 2
#I  # of immediate descendants of order 2^6 is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 2
#I  # of immediate descendants of order 2^7 is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2
#I  Order: 2^7
#I  Nuclear rank: 3
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 3
#I  # of immediate descendants of order 2^9 is 3
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 2^10 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #5;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #2;1
#I  Order: 2^6
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #5;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #4;2
#I  Order: 2^9
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #7;3 #2;2 #4;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #5;2
#I  Order: 2^9
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #7;3 #2;2 #5;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #6;2
#I  Order: 2^9
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^10 is 2
#I  # of immediate descendants of order 2^11 is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #7;3
#I  Order: 2^10
#I  Nuclear rank: 2
#I  2-multiplicator rank: 2
#I  # of immediate descendants of order 2^11 is 1
#I  # of immediate descendants of order 2^12 is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #6;2 #1;1
#I  Order: 2^10
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #6;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #6;2 #2;1
#I  Order: 2^10
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #6;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #6;2 #3;2
#I  Order: 2^11
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #7;3 #2;2 #6;2 #3;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #6;2 #4;2
#I  Order: 2^11
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #7;3 #2;2 #6;2 #4;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #7;3 #1;1
#I  Order: 2^11
#I  Nuclear rank: 0
#I  2-multiplicator rank: 1
#I  Group [grp] #7;3 #2;2 #7;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #2;2 #7;3 #2;2
#I  Order: 2^12
#I  Nuclear rank: 0
#I  2-multiplicator rank: 2
#I  Group [grp] #7;3 #2;2 #7;3 #2;2 is an invalid starting group
26

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-PG-e4-i.tst", 1 );
