# Generated by tst/make_example_tests.g from examples/2gp-SP-Rel-i
gap> START_TEST( "2gp-SP-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^4", "b^4", "[b, a, a]" ];
[ "a^4", "b^4", "[b, a, a]" ]
gap> procId := PqStart(F : Prime := 2, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1, OutputLevel := 3);;
#I  Lower exponent-2 central series for [grp]
#I  Defining relation was 1
#I  Defining relation was 2
#I  Defining relation was 3
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group defining relations:
#I  4 1
#I  0
#I  4 2
#I  0
#I  1 [ 2 1 1 ]
#I  0
#I  Relationship between group defining generators and consistent
#I  power-commutator presentation generators:
#I  1    = .1
#I  1^-1 = .1
#I  2    = .2
#I  2^-1 = .2
#I  Values of power-commutator presentation generators
#I  Class 1
#I  1 is defined on image of defining generator 1
#I  2 is defined on image of defining generator 2
#I  The number of new generators introduced for weight 2 is 3
gap> PqSPStandardPresentation(procId, [ [[0,1],
>                                     [1,1]],
> 
>                                    [[0,1],
>                                     [1,0]] ]
> 
>                          : # options
>                            ClassBound := 10,
>                            PcgsAutomorphisms);;
#I  Starting group has order 2^2; its automorphism group order is 6 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 
#I  2 ---> 0 1 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 2 2-quotient is
#I  Group: [grp] #1;3 to lower exponent-2 central class 2 has order 2^5
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  Subset of automorphism group to check has order bound 96
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 
#I  2 ---> 0 1 0 0 0 
#I  Non-standard label is 3
#I  Required step size is 2
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 3 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 0 1 0 0 0 
#I  2 ---> 1 1 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 
#I  2 ---> 0 1 0 0 0 
#I  Non-standard label is 6
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 6 has orbit representative 1
#I  The standard presentation for the class 3 2-quotient is
#I  Group: G #1;2 to lower exponent-2 central class 3 has order 2^7
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .5, .1 ] = .6 .7
#I  Subset of automorphism group to check has order bound 32
#I  The standard automorphism is:
#I  1 ---> 1 1 1 0 0 0 0 
#I  2 ---> 0 1 1 1 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 1
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 
#I  Non-standard label is 2
#I  Required step size is 1
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 2 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 
#I  2 ---> 0 1 0 1 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 1
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 1
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 4 2-quotient is
#I  Group: G #1;1 to lower exponent-2 central class 4 has order 2^8
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8
#I  [ .5, .1 ] = .6 .7
#I  [ .6, .1 ] = .8
#I  [ .7, .1 ] = .8
#I  Subset of automorphism group to check has order bound 32
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 5 2-quotient is
#I  Group: G #1;2 to lower exponent-2 central class 5 has order 2^10
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9
#I   .7^2 = .9
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10
#I  [ .6, .3 ] = .10
#I  [ .6, .4 ] = .9
#I  [ .7, .1 ] = .8 .9 .10
#I  [ .7, .2 ] = .10
#I  [ .7, .3 ] = .10
#I  [ .7, .4 ] = .9
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  Subset of automorphism group to check has order bound 256
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 
#I  Non-standard label is 4
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 4 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 1 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 6 2-quotient is
#I  Group: G #1;2 to lower exponent-2 central class 6 has order 2^12
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9 .12
#I   .7^2 = .9 .12
#I   .8^2 = .11
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9 .11 .12
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10 .12
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10
#I  [ .6, .3 ] = .10
#I  [ .6, .4 ] = .9 .11
#I  [ .7, .1 ] = .8 .9 .10 .11 .12
#I  [ .7, .2 ] = .10
#I  [ .7, .3 ] = .10
#I  [ .7, .4 ] = .9 .12
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  [ .8, .3 ] = .12
#I  [ .8, .4 ] = .11
#I  [ .9, .1 ] = .11
#I  [ .10, .1 ] = .12
#I  Subset of automorphism group to check has order bound 256
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 7 2-quotient is
#I  Group: G #1;2 to lower exponent-2 central class 7 has order 2^14
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9 .12 .14
#I   .7^2 = .9 .12
#I   .8^2 = .11 .13
#I   .9^2 = .13
#I   .10^2 = .13
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9 .11 .12 .14
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10 .12 .13 .14
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10 .14
#I  [ .6, .3 ] = .10 .13
#I  [ .6, .4 ] = .9 .11 .13
#I  [ .6, .5 ] = .13 .14
#I  [ .7, .1 ] = .8 .9 .10 .11 .12 .14
#I  [ .7, .2 ] = .10 .13 .14
#I  [ .7, .3 ] = .10
#I  [ .7, .4 ] = .9 .12 .13
#I  [ .7, .5 ] = .13 .14
#I  [ .7, .6 ] = .13 .14
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  [ .8, .3 ] = .12
#I  [ .8, .4 ] = .11 .13
#I  [ .8, .5 ] = .13 .14
#I  [ .9, .1 ] = .11
#I  [ .9, .2 ] = .13 .14
#I  [ .9, .3 ] = .13
#I  [ .9, .4 ] = .13
#I  [ .10, .1 ] = .12
#I  [ .10, .2 ] = .14
#I  [ .10, .3 ] = .14
#I  [ .10, .4 ] = .13
#I  [ .11, .1 ] = .13
#I  [ .11, .2 ] = .13
#I  [ .12, .1 ] = .13
#I  [ .12, .2 ] = .14
#I  Subset of automorphism group to check has order bound 512
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 4
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 4 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 1 1 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 2
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 8 2-quotient is
#I  Group: G #1;2 to lower exponent-2 central class 8 has order 2^16
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9 .12 .14 .15 .16
#I   .7^2 = .9 .12 .15 .16
#I   .8^2 = .11 .13
#I   .9^2 = .13 .15
#I   .10^2 = .13
#I   .11^2 = .15
#I   .12^2 = .15
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9 .11 .12 .14 .16
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10 .12 .13 .14 .15 .16
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10 .14
#I  [ .6, .3 ] = .10 .13
#I  [ .6, .4 ] = .9 .11 .13
#I  [ .6, .5 ] = .13 .14
#I  [ .7, .1 ] = .8 .9 .10 .11 .12 .14 .16
#I  [ .7, .2 ] = .10 .13 .14
#I  [ .7, .3 ] = .10
#I  [ .7, .4 ] = .9 .12 .13 .15 .16
#I  [ .7, .5 ] = .13 .14
#I  [ .7, .6 ] = .13 .14
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  [ .8, .3 ] = .12 .16
#I  [ .8, .4 ] = .11 .13 .15
#I  [ .8, .5 ] = .13 .14
#I  [ .8, .6 ] = .15 .16
#I  [ .9, .1 ] = .11
#I  [ .9, .2 ] = .13 .14
#I  [ .9, .3 ] = .13 .16
#I  [ .9, .4 ] = .13 .15
#I  [ .10, .1 ] = .12
#I  [ .10, .2 ] = .14
#I  [ .10, .3 ] = .14
#I  [ .10, .4 ] = .13
#I  [ .11, .1 ] = .13
#I  [ .11, .2 ] = .13
#I  [ .11, .3 ] = .15
#I  [ .11, .4 ] = .15
#I  [ .12, .1 ] = .13 .15
#I  [ .12, .2 ] = .14
#I  [ .12, .3 ] = .16
#I  [ .12, .4 ] = .15
#I  [ .13, .1 ] = .15
#I  [ .14, .1 ] = .16
#I  Subset of automorphism group to check has order bound 512
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 9 2-quotient is
#I  Group: G #1;3 to lower exponent-2 central class 9 has order 2^19
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9 .12 .14 .15 .16
#I   .7^2 = .9 .12 .15 .16
#I   .8^2 = .11 .13 .17 .18
#I   .9^2 = .13 .15
#I   .10^2 = .13 .19
#I   .11^2 = .15 .17
#I   .12^2 = .15
#I   .13^2 = .17
#I   .14^2 = .17
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9 .11 .12 .14 .16 .18
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10 .12 .13 .14 .15 .16 .18 .19
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10 .14 .19
#I  [ .6, .3 ] = .10 .13
#I  [ .6, .4 ] = .9 .11 .13 .17 .18
#I  [ .6, .5 ] = .13 .14
#I  [ .7, .1 ] = .8 .9 .10 .11 .12 .14 .16 .17 .18 .19
#I  [ .7, .2 ] = .10 .13 .14 .17 .18
#I  [ .7, .3 ] = .10 .18 .19
#I  [ .7, .4 ] = .9 .12 .13 .15 .16 .17
#I  [ .7, .5 ] = .13 .14
#I  [ .7, .6 ] = .13 .14
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  [ .8, .3 ] = .12 .16
#I  [ .8, .4 ] = .11 .13 .15
#I  [ .8, .5 ] = .13 .14 .17 .19
#I  [ .8, .6 ] = .15 .16 .18 .19
#I  [ .8, .7 ] = .17 .18
#I  [ .9, .1 ] = .11
#I  [ .9, .2 ] = .13 .14 .17 .18
#I  [ .9, .3 ] = .13 .16 .18
#I  [ .9, .4 ] = .13 .15 .17
#I  [ .9, .5 ] = .17 .19
#I  [ .9, .6 ] = .17 .18
#I  [ .9, .7 ] = .17 .18
#I  [ .10, .1 ] = .12
#I  [ .10, .2 ] = .14 .17
#I  [ .10, .3 ] = .14 .19
#I  [ .10, .4 ] = .13 .18 .19
#I  [ .10, .5 ] = .17 .19
#I  [ .10, .6 ] = .18 .19
#I  [ .10, .7 ] = .17 .18
#I  [ .10, .8 ] = .17 .18
#I  [ .11, .1 ] = .13
#I  [ .11, .2 ] = .13 .18 .19
#I  [ .11, .3 ] = .15 .17
#I  [ .11, .4 ] = .15 .17
#I  [ .12, .1 ] = .13 .15 .18 .19
#I  [ .12, .2 ] = .14
#I  [ .12, .3 ] = .16 .17 .19
#I  [ .12, .4 ] = .15
#I  [ .12, .5 ] = .17 .19
#I  [ .12, .6 ] = .17 .18
#I  [ .12, .7 ] = .17 .18
#I  [ .13, .1 ] = .15
#I  [ .13, .2 ] = .17
#I  [ .13, .3 ] = .17
#I  [ .13, .4 ] = .17
#I  [ .14, .1 ] = .16
#I  [ .14, .2 ] = .19
#I  [ .14, .3 ] = .19
#I  [ .14, .4 ] = .18
#I  [ .15, .1 ] = .17
#I  [ .15, .2 ] = .17
#I  [ .16, .1 ] = .18
#I  [ .16, .2 ] = .19
#I  Subset of automorphism group to check has order bound 8192
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 1
#I  Rank of characteristic subgroup is 1
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 2
#I  Rank of characteristic subgroup is 2
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 3
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 5
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 5 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Non-standard label is 4
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 4 has orbit representative 1
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Non-standard label is 1
#I  Required step size is 3
#I  Relative step size is 3
#I  Rank of characteristic subgroup is 4
#I  The non-standard subgroup 1 has orbit representative 1
#I  The standard presentation for the class 10 2-quotient is
#I  Group: G #1;3 to lower exponent-2 central class 10 has order 2^22
#I  Non-trivial powers:
#I   .1^2 = .4
#I   .2^2 = .5
#I   .3^2 = .6 .7
#I   .6^2 = .9 .12 .14 .15 .16 .20 .21
#I   .7^2 = .9 .12 .15 .16 .20 .21
#I   .8^2 = .11 .13 .17 .18
#I   .9^2 = .13 .15
#I   .10^2 = .13 .19 .20 .22
#I   .11^2 = .15 .17
#I   .12^2 = .15 .22
#I   .13^2 = .17 .20
#I   .14^2 = .17 .20
#I   .15^2 = .20
#I   .16^2 = .20
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .9 .11 .12 .14 .16 .18 .21 .22
#I  [ .5, .1 ] = .6 .7
#I  [ .5, .4 ] = .9 .10 .12 .13 .14 .15 .16 .18 .19 .20 .21 .22
#I  [ .6, .1 ] = .8
#I  [ .6, .2 ] = .10 .14 .19
#I  [ .6, .3 ] = .10 .13 .20 .22
#I  [ .6, .4 ] = .9 .11 .13 .17 .18
#I  [ .6, .5 ] = .13 .14 .20 .22
#I  [ .7, .1 ] = .8 .9 .10 .11 .12 .14 .16 .17 .18 .19 .20 .21 .22
#I  [ .7, .2 ] = .10 .13 .14 .17 .18 .20 .22
#I  [ .7, .3 ] = .10 .18 .19 .20
#I  [ .7, .4 ] = .9 .12 .13 .15 .16 .17 .20 .21 .22
#I  [ .7, .5 ] = .13 .14 .20 .22
#I  [ .7, .6 ] = .13 .14 .20 .22
#I  [ .8, .1 ] = .9
#I  [ .8, .2 ] = .10
#I  [ .8, .3 ] = .12 .16 .22
#I  [ .8, .4 ] = .11 .13 .15
#I  [ .8, .5 ] = .13 .14 .17 .19 .22
#I  [ .8, .6 ] = .15 .16 .18 .19 .20
#I  [ .8, .7 ] = .17 .18
#I  [ .9, .1 ] = .11
#I  [ .9, .2 ] = .13 .14 .17 .18 .20 .22
#I  [ .9, .3 ] = .13 .16 .18 .20
#I  [ .9, .4 ] = .13 .15 .17
#I  [ .9, .5 ] = .17 .19 .20
#I  [ .9, .6 ] = .17 .18 .20 .22
#I  [ .9, .7 ] = .17 .18
#I  [ .9, .8 ] = .20 .21
#I  [ .10, .1 ] = .12
#I  [ .10, .2 ] = .14 .17 .20
#I  [ .10, .3 ] = .14 .19
#I  [ .10, .4 ] = .13 .18 .19 .22
#I  [ .10, .5 ] = .17 .19 .20
#I  [ .10, .6 ] = .18 .19 .20
#I  [ .10, .7 ] = .17 .18
#I  [ .10, .8 ] = .17 .18
#I  [ .11, .1 ] = .13
#I  [ .11, .2 ] = .13 .18 .19 .22
#I  [ .11, .3 ] = .15 .17 .20 .21 .22
#I  [ .11, .4 ] = .15 .17 .20
#I  [ .12, .1 ] = .13 .15 .18 .19 .20
#I  [ .12, .2 ] = .14
#I  [ .12, .3 ] = .16 .17 .19
#I  [ .12, .4 ] = .15 .21 .22
#I  [ .12, .5 ] = .17 .19 .20
#I  [ .12, .6 ] = .17 .18 .20 .22
#I  [ .12, .7 ] = .17 .18
#I  [ .12, .8 ] = .20 .21
#I  [ .13, .1 ] = .15
#I  [ .13, .2 ] = .17 .20
#I  [ .13, .3 ] = .17 .20
#I  [ .13, .4 ] = .17 .20
#I  [ .14, .1 ] = .16
#I  [ .14, .2 ] = .19
#I  [ .14, .3 ] = .19
#I  [ .14, .4 ] = .18 .20
#I  [ .15, .1 ] = .17
#I  [ .15, .2 ] = .17 .20
#I  [ .15, .3 ] = .20
#I  [ .15, .4 ] = .20
#I  [ .16, .1 ] = .18
#I  [ .16, .2 ] = .19
#I  [ .16, .3 ] = .22
#I  [ .16, .4 ] = .21
#I  [ .17, .1 ] = .20
#I  [ .18, .1 ] = .21
#I  [ .19, .1 ] = .22
#I  Subset of automorphism group to check has order bound 8192
#I  The standard automorphism is:
#I  1 ---> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  0 
#I  2 ---> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  0 

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-SP-Rel-i.tst", 1 );
