# Generated by tst/make_example_tests.g from examples/2gp-Rel
gap> START_TEST( "2gp-Rel.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := [ "[b, a, a]", "(a * b * a)^4"];
[ "[b, a, a]", "(a * b * a)^4" ]
gap> Pq( F : Prime := 2, ClassBound := 6, Relators := rels, 
>         OutputLevel := 1 );
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^8
#I  Group: [grp] to lower exponent-2 central class 4 has order 2^11
#I  Group: [grp] to lower exponent-2 central class 5 has order 2^15
#I  Group: [grp] to lower exponent-2 central class 6 has order 2^19
<pc group of size 524288 with 19 generators>

# interactive form: PqExample( "2gp-Rel", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := [ "[b, a, a]", "(a * b * a)^4"];
[ "[b, a, a]", "(a * b * a)^4" ]
gap> procId := PqStart( F );
1
gap> Pq( procId : Prime := 2, ClassBound := 6, Relators := rels, 
>         OutputLevel := 1 );
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^8
#I  Group: [grp] to lower exponent-2 central class 4 has order 2^11
#I  Group: [grp] to lower exponent-2 central class 5 has order 2^15
#I  Group: [grp] to lower exponent-2 central class 6 has order 2^19
<pc group of size 524288 with 19 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-Rel.tst", 1 );
