# Generated by tst/make_example_tests.g from examples/2gp-PG-i
gap> START_TEST( "2gp-PG-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 2);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
gap> PqPGSupplyAutomorphisms(procId, [ [[0,1],
>                                    [1,1]],
> 
>                                   [[0,1],
>                                    [1,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 7,
>                                   OrderBound := 8,
>                                   PcgsAutomorphisms,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 2^2
#I  Nuclear rank: 3
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^3 is 3
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^4 is 3
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^5 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1
#I  Order: 2^3
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^4 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1
#I  Order: 2^3
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^4 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2
#I  Order: 2^4
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^5 is 2
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2
#I  Order: 2^4
#I  Nuclear rank: 3
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^5 is 7
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^6 is 11
#I  # of capable immediate descendants is 10
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #6;2
#I  Order: 2^4
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^5 is 4
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3
#I  Order: 2^5
#I  Nuclear rank: 5
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 9
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^7 is 37
#I  # of capable immediate descendants is 28
#I  # of immediate descendants of order 2^8 is 37
#I  # of capable immediate descendants is 37
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1
#I  Order: 2^4
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^5 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1
#I  Order: 2^4
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^5 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #2;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^8 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^6 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #5;2 #5;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 5
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 8
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 7
#I  # of capable immediate descendants is 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #5;2 #11;2
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 12
#I  # of capable immediate descendants is 4
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 16
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #14;2
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 2^8 is 7
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #5;2 #17;2
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #18;2
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #19;3
#I  Order: 2^7
#I  Nuclear rank: 4
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3
#I  Order: 2^7
#I  Nuclear rank: 3
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 10
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #5;2 #21;3
#I  Order: 2^7
#I  Nuclear rank: 3
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #2;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #6;2 #5;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^8 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #5;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 10
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #10;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #11;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #12;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #13;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #14;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 12
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #15;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #16;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #17;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 12
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #18;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #19;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 10
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #7;3 #20;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #21;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #23;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #25;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #26;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 12
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #27;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #29;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #30;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2
#I  Order: 2^7
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #7;3 #32;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #7;3 #33;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #37;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #7;3 #38;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #39;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 14
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #40;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #41;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #44;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #46;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #47;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #47;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #48;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #48;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #49;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #49;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #50;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #50;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #51;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #51;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #52;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #52;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #53;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #53;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #54;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #54;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #55;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #55;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #56;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #56;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #57;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #57;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #58;3
#I  Order: 2^8
#I  Nuclear rank: 4
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #58;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #59;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #59;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #60;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #60;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #61;3
#I  Order: 2^8
#I  Nuclear rank: 4
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #61;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #62;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #62;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #63;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #63;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #64;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #64;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #65;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #65;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #66;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #66;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #67;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #67;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #68;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #68;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #69;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #69;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #70;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #70;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #71;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #71;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #72;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #72;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #73;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #73;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #74;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #74;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #75;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #75;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #76;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #76;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #77;3
#I  Order: 2^8
#I  Nuclear rank: 4
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #77;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #78;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #78;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #79;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #79;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #80;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #80;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #81;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #81;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #82;3
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #82;3 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #83;3
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #83;3 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^6 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #3;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #3;2 #3;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #4;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #3;2 #4;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2 #3;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #4;2 #3;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #3;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #4;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 3
#I  **************************************************
#I  Starting group: [grp] #5;2 #5;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 10
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #9;2
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 #9;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #10;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #10;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #11;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #12;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #13;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #14;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #8;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #15;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #16;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #8;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 5
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #8;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #8;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #9;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #9;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #10;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #10;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #11;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #9;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #12;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #13;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #9;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #9;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #10;2 #9;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #10;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #10;2 #10;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #11;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #10;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #12;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #10;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #13;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #10;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #15;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #10;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #11;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #5;1
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #9;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #13;2
#I  Order: 2^8
#I  Nuclear rank: 3
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #12;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #14;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #15;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #16;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #17;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #17;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #18;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #19;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #19;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #20;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #20;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #21;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #21;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #22;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #22;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #23;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #23;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #24;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #25;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #25;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #26;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #26;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #27;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #27;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #28;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #12;2 #28;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #7;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #16;2 #7;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #9;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #16;2 #9;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #11;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #16;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #12;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #16;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #13;2
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #16;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #17;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #17;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #19;3 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #19;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #19;3 #2;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #5;2 #19;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #19;3 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #19;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #19;3 #11;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #19;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #20;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #20;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #20;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3 #5;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #20;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #20;3 #6;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #20;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #21;3 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #21;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #21;3 #4;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #21;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #21;3 #5;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #21;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #5;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #5;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #5;2 #4;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #5;2 #4;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #5;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #5;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #6;2
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #6;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #5;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 10
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 16
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^8 is 12
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;3 #10;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #10;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #10;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #10;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #11;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #11;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #11;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #11;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #11;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #11;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #12;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #12;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #12;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #12;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #13;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #13;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #13;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #13;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #14;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #14;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #14;2 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #14;2 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #14;2 #6;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #14;2 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #15;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #15;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #16;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #16;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #16;2 #5;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #16;2 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #16;2 #12;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #16;2 #12;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #17;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #17;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #17;2 #5;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #17;2 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #17;2 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #17;2 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #18;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #18;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #18;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #18;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #19;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #19;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #19;2 #5;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #19;2 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #19;2 #6;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #19;2 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #19;2 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #19;2 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #20;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #20;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #21;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #21;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #21;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #21;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #21;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #21;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #23;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #23;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #23;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #23;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #26;2 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #26;2 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #26;2 #10;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #26;2 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #26;2 #11;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #26;2 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #29;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #29;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #29;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #29;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #30;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #30;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #30;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #30;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #30;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #30;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #31;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #31;2 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #31;2 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2 #10;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #31;2 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #31;2 #15;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #7;3 #31;2 #15;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #32;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #32;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #32;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #32;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #32;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #32;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #32;2 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #32;2 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #33;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #33;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #33;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #33;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #37;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #7;3 #37;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #37;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #37;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #37;2 #9;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #37;2 #9;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #39;2 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #39;2 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #40;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #40;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #40;2 #2;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #40;2 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #41;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #41;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #41;2 #3;1
#I  Order: 2^8
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #41;2 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #44;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #44;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #44;2 #5;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #44;2 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #46;2 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #46;2 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #46;2 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #7;3 #46;2 #7;1 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #1;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #3;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #1;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #3;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #3;2 #2;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #3;2 #2;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #4;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #4;2 #1;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #4;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 8
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #1;1 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #3;1 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #3;1 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 4
#I  **************************************************
#I  Starting group: [grp] #5;2 #5;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  # of immediate descendants of order 2^8 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #3;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #3;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 #3;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #3;1 #7;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 #3;1 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #3;1 #8;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 #3;1 #8;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #4;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #4;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #4;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #4;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #5;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #5;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #5;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #5;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #5;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #5;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2 #5;1 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #8;2 #5;1 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #3;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #4;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #4;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #4;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #4;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #5;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #5;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2 #5;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #9;2 #5;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #10;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #3;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #10;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2 #3;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #10;2 #3;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #11;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #11;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #5;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #12;2 #5;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #5;1 #9;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #12;2 #5;1 #9;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #5;1 #10;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #12;2 #5;1 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #5;1 #15;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #12;2 #5;1 #15;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #6;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #6;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #7;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #7;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #7;1 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #7;1 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #12;2 #9;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #12;2 #9;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #13;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #1;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #13;2 #1;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #1;1 #5;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #13;2 #1;1 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #2;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #13;2 #2;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #2;1 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #13;2 #2;1 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #4;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #13;2 #4;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #13;2 #4;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #13;2 #4;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #16;2 #5;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #16;2 #5;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #17;2 #2;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #17;2 #2;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #17;2 #2;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #5;2 #17;2 #2;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #1;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #5;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #5;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #2;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #2;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #2;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #2;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #6;2 #3;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #6;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #5;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #5;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #1;1 #5;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #1;1 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #1;1 #9;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #1;1 #9;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #1;1 #13;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #1;1 #13;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #4;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #4;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;3 #7;1 #4;1 #8;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;3 #7;1 #4;1 #8;1 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1 #1;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1 #1;1 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  # of immediate descendants of order 2^8 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #1;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #4;2 #1;1 #1;1 #1;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #4;2 #1;1 #1;1 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #1;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #2;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #3;1 #3;1 #3;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #2;1 #3;1 #3;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1 #3;1 #3;1 #4;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #2;1 #3;1 #3;1 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #5;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 4
#I  Group [grp] #5;2 #5;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #1;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #1;1 #1;1 #1;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #3;1 #1;1 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;1 #1;1 #1;1 #2;1
#I  Order: 2^8
#I  Nuclear rank: 1
#I  2-multiplicator rank: 3
#I  Group [grp] #6;2 #3;1 #1;1 #1;1 #2;1 is an invalid starting group
#I  **************************************************
355

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-PG-i.tst", 1 );
