# Generated by tst/make_example_tests.g from examples/2gp-a-Rel-i
gap> START_TEST( "2gp-a-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup(3, "x");
<free group on the generators [ x1, x2, x3 ]>
gap> rels := ["x1^x2 * x3", "[x2, x1, x1]", 
>          "[x2 * [x2, x1] * x1^2, x1 * x2 ]"];
[ "x1^x2 * x3", "[x2, x1, x1]", "[x2 * [x2, x1] * x1^2, x1 * x2 ]" ]
gap> procId := PqStart(F : Prime := 2, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 3, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^4
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^6

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-a-Rel-i.tst", 1 );
