# Generated by tst/make_example_tests.g from examples/2gp-Rel-i
gap> START_TEST( "2gp-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["[b, a, a]", "(a * b * a)^4"];
[ "[b, a, a]", "(a * b * a)^4" ]
gap> procId := PqStart(F : Prime := 2, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 6, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^8
#I  Group: [grp] to lower exponent-2 central class 4 has order 2^11
#I  Group: [grp] to lower exponent-2 central class 5 has order 2^15
#I  Group: [grp] to lower exponent-2 central class 6 has order 2^19
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-Rel-i.tst", 1 );
