# Generated by tst/make_example_tests.g from examples/2gp-PG-3-i
gap> START_TEST( "2gp-PG-3-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c");
<free group on the generators [ a, b, c ]>
gap> procId := PqStart(F : Prime := 2);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^3
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^9
gap> PqPGSupplyAutomorphisms(procId, [ [[1,1,0],
>                                    [0,1,0],
>                                    [0,0,1]],
> 
>                                   [[0,0,1],
>                                    [1,0,0],
>                                    [0,1,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 5,
>                                   OrderBound := 7,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 2^3
#I  Nuclear rank: 6
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^4 is 4
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^5 is 15
#I  # of capable immediate descendants is 13
#I  # of immediate descendants of order 2^6 is 28
#I  # of capable immediate descendants is 28
#I  # of immediate descendants of order 2^7 is 15
#I  # of capable immediate descendants is 15
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1
#I  Order: 2^4
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^5 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1
#I  Order: 2^4
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^5 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 4
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^7 is 9
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #6;2
#I  Order: 2^5
#I  Nuclear rank: 3
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^6 is 16
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^7 is 106
#I  # of capable immediate descendants is 54
#I  **************************************************
#I  Starting group: [grp] #7;2
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 9
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^7 is 13
#I  # of capable immediate descendants is 9
#I  **************************************************
#I  Starting group: [grp] #8;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #9;2
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 11
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 2^7 is 20
#I  # of capable immediate descendants is 10
#I  **************************************************
#I  Starting group: [grp] #10;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #11;2
#I  Order: 2^5
#I  Nuclear rank: 3
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^6 is 12
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^7 is 70
#I  # of capable immediate descendants is 25
#I  **************************************************
#I  Starting group: [grp] #12;2
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 15
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 2^7 is 40
#I  # of capable immediate descendants is 13
#I  **************************************************
#I  Starting group: [grp] #13;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #14;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #15;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #18;2
#I  Order: 2^5
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 2^7 is 19
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #19;2
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^6 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #20;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #21;3
#I  Order: 2^6
#I  Nuclear rank: 5
#I  2-multiplicator rank: 8
#I  # of immediate descendants of order 2^7 is 17
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #22;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #23;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 18
#I  # of capable immediate descendants is 7
#I  **************************************************
#I  Starting group: [grp] #24;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 13
#I  # of capable immediate descendants is 7
#I  **************************************************
#I  Starting group: [grp] #25;3
#I  Order: 2^6
#I  Nuclear rank: 6
#I  2-multiplicator rank: 9
#I  # of immediate descendants of order 2^7 is 18
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #26;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 20
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #27;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 14
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #28;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #29;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #30;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #31;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 19
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #32;3
#I  Order: 2^6
#I  Nuclear rank: 5
#I  2-multiplicator rank: 8
#I  # of immediate descendants of order 2^7 is 47
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #33;3
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 7
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #34;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 16
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #35;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 15
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #36;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 30
#I  # of capable immediate descendants is 8
#I  **************************************************
#I  Starting group: [grp] #37;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 15
#I  # of capable immediate descendants is 7
#I  **************************************************
#I  Starting group: [grp] #38;3
#I  Order: 2^6
#I  Nuclear rank: 5
#I  2-multiplicator rank: 8
#I  # of immediate descendants of order 2^7 is 24
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #39;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 10
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #40;3
#I  Order: 2^6
#I  Nuclear rank: 4
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 24
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #41;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #42;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #43;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 12
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #44;3
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 6
#I  **************************************************
#I  Starting group: [grp] #45;3
#I  Order: 2^6
#I  Nuclear rank: 3
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #46;3
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 5
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  Starting group: [grp] #47;3
#I  Order: 2^6
#I  Nuclear rank: 2
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 1
#I  **************************************************
#I  Starting group: [grp] #48;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #48;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #49;4
#I  Order: 2^7
#I  Nuclear rank: 8
#I  2-multiplicator rank: 10
#I  Group [grp] #49;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #50;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #50;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #51;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #51;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #52;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #52;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #53;4
#I  Order: 2^7
#I  Nuclear rank: 7
#I  2-multiplicator rank: 9
#I  Group [grp] #53;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #54;4
#I  Order: 2^7
#I  Nuclear rank: 8
#I  2-multiplicator rank: 10
#I  Group [grp] #54;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #55;4
#I  Order: 2^7
#I  Nuclear rank: 7
#I  2-multiplicator rank: 9
#I  Group [grp] #55;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #56;4
#I  Order: 2^7
#I  Nuclear rank: 7
#I  2-multiplicator rank: 9
#I  Group [grp] #56;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #57;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #57;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #58;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #58;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #59;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #59;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #60;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #60;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #61;4
#I  Order: 2^7
#I  Nuclear rank: 6
#I  2-multiplicator rank: 8
#I  Group [grp] #61;4 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #62;4
#I  Order: 2^7
#I  Nuclear rank: 7
#I  2-multiplicator rank: 9
#I  Group [grp] #62;4 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1
#I  Order: 2^5
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^6 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #5;2 #5;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #5;2 #5;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #6;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #5;2 #6;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #7;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #7;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #8;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #8;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #9;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #9;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #10;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #5;2 #10;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 7
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #4;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 18
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #6;2 #9;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 13
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #6;2 #17;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #17;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #18;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #19;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #19;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #20;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #20;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #21;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #21;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #22;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #22;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #23;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #23;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #24;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #25;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #25;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #26;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #26;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #27;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #27;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #28;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #28;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #29;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #29;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #32;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #32;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #33;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #33;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #35;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #35;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #43;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #43;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #46;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #46;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #51;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #51;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #52;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #52;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #53;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #53;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #54;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #54;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #58;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #58;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #59;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #59;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #60;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #60;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #64;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #64;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #68;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #68;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #71;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #71;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #75;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #75;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #76;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #76;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #77;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #77;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #78;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #78;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #79;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #79;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #80;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #80;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #81;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #81;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #87;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #87;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #91;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #91;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #93;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #93;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #99;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #99;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #100;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #100;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #102;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #102;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #103;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #103;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #105;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #105;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #106;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #106;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #108;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #108;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #109;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #109;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #111;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #111;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #112;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #112;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #114;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #114;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #115;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #115;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #117;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #117;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #118;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #118;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #120;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #120;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #121;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #6;2 #121;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 5
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;2 #4;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #7;2 #5;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #7;2 #10;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #7;2 #10;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #11;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #7;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #12;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #13;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #14;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #15;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #16;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #18;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #19;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #7;2 #19;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #8;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #8;2 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #9;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 5
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #9;2 #3;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 8
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #9;2 #8;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #9;2 #12;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #9;2 #12;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #13;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #14;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #15;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #16;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #17;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #9;2 #17;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #18;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #23;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #23;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #24;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #29;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #9;2 #29;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #10;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #11;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 12
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #11;2 #11;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  # of immediate descendants of order 2^7 is 10
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #11;2 #13;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #11;2 #13;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #14;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #15;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #16;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #11;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #17;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #17;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #18;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #19;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #19;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #20;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #20;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #21;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #21;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #22;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #22;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #23;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #23;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #24;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #25;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #25;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #28;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #28;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #31;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #31;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #34;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #34;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #41;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 7
#I  Group [grp] #11;2 #41;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #43;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #43;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #47;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #47;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #49;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #49;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #51;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #51;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #61;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #61;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #63;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #63;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #69;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #69;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #71;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #11;2 #71;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 9
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #12;2 #8;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 9
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #12;2 #16;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #16;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #18;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #12;2 #18;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #19;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #19;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #20;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #20;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #24;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #25;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #25;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #26;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #26;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #28;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #28;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #32;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #32;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #33;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #33;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #36;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #36;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #38;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #38;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #40;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #12;2 #40;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #13;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #13;2 #3;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #14;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #14;2 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 2
#I  **************************************************
#I  Starting group: [grp] #15;2 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #18;2 #2;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #18;2 #8;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #18;2 #8;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #11;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #18;2 #11;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #14;2
#I  Order: 2^7
#I  Nuclear rank: 2
#I  2-multiplicator rank: 6
#I  Group [grp] #18;2 #14;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #15;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #18;2 #15;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #23;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #18;2 #23;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #24;2
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #18;2 #24;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #19;2 #3;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  # of immediate descendants of order 2^7 is 4
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #20;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #20;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #20;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #20;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #20;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #20;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #21;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #21;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #21;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #21;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #21;3 #11;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #21;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #22;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #22;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #22;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #22;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #22;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #22;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #13;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #13;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #23;3 #15;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #23;3 #15;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #9;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #9;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #10;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #24;3 #11;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #24;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #25;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 9
#I  Group [grp] #25;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #25;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 9
#I  Group [grp] #25;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #25;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 9
#I  Group [grp] #25;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #25;3 #8;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 9
#I  Group [grp] #25;3 #8;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #25;3 #12;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 9
#I  Group [grp] #25;3 #12;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #8;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #8;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #11;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #26;3 #12;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #26;3 #12;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #27;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #27;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #27;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #27;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #27;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #27;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #27;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #27;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #27;3 #8;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #27;3 #8;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #28;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #28;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #28;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #28;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #28;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #28;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #28;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #28;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #29;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #29;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #30;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #30;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #30;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #30;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #30;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #30;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #30;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #30;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #30;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #30;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #10;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #15;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #15;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #31;3 #17;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #31;3 #17;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #11;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #21;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #21;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #25;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #25;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #32;3 #30;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #32;3 #30;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #33;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #33;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #12;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #12;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #34;3 #14;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #34;3 #14;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #35;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #35;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #35;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #35;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #35;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #35;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #35;3 #9;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #35;3 #9;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #35;3 #10;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #35;3 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #8;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #8;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #11;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #11;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #17;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #17;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #19;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #19;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #36;3 #29;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #36;3 #29;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #10;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #10;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #37;3 #13;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #37;3 #13;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #38;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #38;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #38;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #38;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #38;3 #13;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 8
#I  Group [grp] #38;3 #13;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #39;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #39;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #39;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #39;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #40;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #40;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #40;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #40;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #40;3 #12;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #40;3 #12;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #40;3 #15;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #40;3 #15;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #40;3 #16;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #40;3 #16;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #41;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #41;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #41;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #41;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #41;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #41;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #42;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #42;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #42;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #42;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #43;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #43;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #43;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #43;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #43;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #43;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #43;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #43;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #43;3 #7;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #43;3 #7;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #5;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #5;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #44;3 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #44;3 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #45;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #45;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #45;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #45;3 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #45;3 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #45;3 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #46;3 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #46;3 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #46;3 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #46;3 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #46;3 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #46;3 #3;1 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 3
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1 #1;1 #1;1
#I  Order: 2^6
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  # of immediate descendants of order 2^7 is 6
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #5;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #5;2 #1;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #5;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #4;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #4;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #4;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #4;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #4;1 #4;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #4;1 #4;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #4;1 #13;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #4;1 #13;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #6;2 #9;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #6;2 #9;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #5;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;2 #5;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #7;2 #5;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #7;2 #5;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #8;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #8;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #8;2 #1;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #8;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #9;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #3;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #9;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #9;2 #3;1 #6;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #9;2 #3;1 #6;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #10;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #10;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #11;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #11;2 #11;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 7
#I  Group [grp] #11;2 #11;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #12;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #12;2 #8;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #12;2 #8;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #13;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #13;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #13;2 #1;1 #3;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #13;2 #1;1 #3;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #14;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #14;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #14;2 #1;1 #2;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #14;2 #1;1 #2;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #15;2 #1;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #15;2 #1;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #18;2 #2;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 6
#I  Group [grp] #18;2 #2;1 #1;1 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #19;2 #3;1 #1;1
#I  Order: 2^7
#I  Nuclear rank: 1
#I  2-multiplicator rank: 5
#I  Group [grp] #19;2 #3;1 #1;1 is an invalid starting group
#I  **************************************************
365

#
gap> PqQuitAll();
gap> STOP_TEST( "2gp-PG-3-i.tst", 1 );
