# Generated by tst/make_example_tests.g from examples/3gp-Rel-i
gap> START_TEST( "3gp-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> rels := ["(b * c^-1 * d)^-3", "(c * d^-1)^3", 
>          "[b, a] * c", "[c, a]", "[c, b] * d"];
[ "(b * c^-1 * d)^-3", "(c * d^-1)^3", "[b, a] * c", "[c, a]", "[c, b] * d" ]
gap> procId := PqStart(F : Prime := 3, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 19, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^4
#I  Group: [grp] to lower exponent-3 central class 3 has order 3^6
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
#I  Group: [grp] to lower exponent-3 central class 5 has order 3^8
#I  Group: [grp] to lower exponent-3 central class 6 has order 3^9
#I  Group: [grp] to lower exponent-3 central class 7 has order 3^10
#I  Group: [grp] to lower exponent-3 central class 8 has order 3^11
#I  Group: [grp] to lower exponent-3 central class 9 has order 3^12
#I  Group: [grp] to lower exponent-3 central class 10 has order 3^13
#I  Group: [grp] to lower exponent-3 central class 11 has order 3^14
#I  Group: [grp] to lower exponent-3 central class 12 has order 3^15
#I  Group: [grp] to lower exponent-3 central class 13 has order 3^16
#I  Group: [grp] to lower exponent-3 central class 14 has order 3^17
#I  Group: [grp] to lower exponent-3 central class 15 has order 3^18
#I  Group: [grp] to lower exponent-3 central class 16 has order 3^19
#I  Group: [grp] to lower exponent-3 central class 17 has order 3^20
#I  Group: [grp] to lower exponent-3 central class 18 has order 3^21
#I  Group: [grp] to lower exponent-3 central class 19 has order 3^22
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-Rel-i.tst", 1 );
