# Generated by tst/make_example_tests.g from examples/3gp-a-x-Rel-i
gap> START_TEST( "3gp-a-x-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^3", "b^3"];
[ "a^3", "b^3" ]
gap> procId := PqStart(F : Prime := 3, Exponent := 9, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 4, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^3
#I  Group: [grp] to lower exponent-3 central class 3 has order 3^5
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
gap> PqDisplayPcPresentation(procId : OutputLevel := 2);;
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
#I  Non-trivial powers:
#I   .3^3 = .6^2
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .4
#I  [ .3, .2 ] = .5
#I  [ .4, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .5, .1 ] = .7
#I  [ .5, .2 ] = .6
gap> PqNextClass(procId);;
#I  Processing tails for generators of weight 4 and 1
#I  Processing tails for generators of weight 3 and 2
#I  The number of new generators introduced for weight 5 is 4
#I  Processing tails for generators of weight 3 and 1
#I  Processing tails for generators of weight 2 and 2
#I  The number of new generators introduced for weight 4 is 2
#I  Generator 12 is redundant
#I  Jacobi was 3 2 1
#I  Processing tails for generators of weight 2 and 1
#I  The number of new generators introduced for weight 3 is 0
#I  Generator 13 is redundant
#I  Jacobi was 2 1 1
#I  The number of new generators introduced for weight 2 is 2
#I  Generator 14 is trivial
#I  Defining relation was 1
#I  Generator 15 is trivial
#I  Defining relation was 2
#I  2 relations of class 1 collected
#I  Generator 9 is redundant
#I  Collected power 9 of the following word: 1^1 2^1 
#I  2 relations of class 2 collected
#I  Generator 8 is trivial
#I  Collected power 9 of the following word: 1^1 2^2 
#I  3 relations of class 3 collected
#I  2 relations of class 4 collected
#I  1 relation of class 5 collected
#I  Group: [grp] to lower exponent-3 central class 5 has order 3^9
#I  Non-trivial powers:
#I   .3^3 = .6^2 .8^2
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .4
#I  [ .3, .2 ] = .5
#I  [ .4, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8
#I  [ .5, .1 ] = .7 .8 .9^2
#I  [ .5, .2 ] = .6 .8 .9^2
#I  [ .5, .3 ] = .9^2
#I  [ .7, .1 ] = .8
#I  [ .7, .2 ] = .9
gap> PqSetOutputLevel(procId, 1);;
gap> PqSetupTablesForNextClass(procId);;
#I  Setup performed for class 6
gap> PqTails(procId, 0);;
gap> PqDoConsistencyChecks(procId, 0, 0);;
gap> PqCollectDefiningRelations(procId);;
gap> PqDoExponentChecks(procId);;
gap> PqEliminateRedundantGenerators(procId);;
gap> PqDisplayPcPresentation(procId : OutputLevel := 2);;
#I  Group: [grp] to lower exponent-3 central class 6 has order 3^11
#I  Non-trivial powers:
#I   .3^3 = .6^2 .8^2 .10 .11
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .4
#I  [ .3, .2 ] = .5
#I  [ .4, .1 ] = .6
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .8 .10^2 .11^2
#I  [ .5, .1 ] = .7 .8 .9^2 .10^2 .11^2
#I  [ .5, .2 ] = .6 .8 .9^2 .10^2
#I  [ .5, .3 ] = .9^2 .11
#I  [ .5, .4 ] = .10 .11
#I  [ .6, .2 ] = .10^2
#I  [ .7, .1 ] = .8
#I  [ .7, .2 ] = .9
#I  [ .7, .3 ] = .10^2 .11
#I  [ .8, .2 ] = .10
#I  [ .9, .1 ] = .11
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-a-x-Rel-i.tst", 1 );
