# Generated by tst/make_example_tests.g from examples/3gp-PG-x-1-i
gap> START_TEST( "3gp-PG-x-1-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 3);;
gap> Pq(procId : ClassBound := 1, 
>                           OutputLevel := 1);
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
<pc group of size 9 with 2 generators>
gap> PqPCover(procId);
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^5
<pc group of size 243 with 5 generators>
gap> PqPGSupplyAutomorphisms(procId, [ [[1,1],
>                                    [0,1]],
> 
>                                   [[0,1],
>                                    [1,0]] ]);;
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 
#I  Generator  4 --> 0 0 0 1 1 
#I  Generator  5 --> 0 0 0 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 0 1 0 0 0 
#I  Generator  2 --> 1 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 
#I  Generator  4 --> 0 0 0 0 1 
#I  Generator  5 --> 0 0 0 1 0 
gap> PqPGConstructDescendants(procId : ClassBound := 3,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 3^2
#I  Nuclear rank: 3
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^3 is 3
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 3^4 is 3
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 3^5 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;1
#I  Order: 3^3
#I  Nuclear rank: 1
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^4 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #2;1
#I  Order: 3^3
#I  Nuclear rank: 2
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^4 is 4
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 3^5 is 7
#I  # of capable immediate descendants is 5
#I  **************************************************
#I  Starting group: [grp] #4;2
#I  Order: 3^4
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^5 is 2
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 3^6 is 2
#I  # of capable immediate descendants is 2
#I  **************************************************
#I  Starting group: [grp] #5;2
#I  Order: 3^4
#I  Nuclear rank: 3
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^5 is 9
#I  # of capable immediate descendants is 5
#I  # of immediate descendants of order 3^6 is 18
#I  # of capable immediate descendants is 16
#I  # of immediate descendants of order 3^7 is 4
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #6;2
#I  Order: 3^4
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^5 is 2
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 3^6 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
#I  Starting group: [grp] #7;3
#I  Order: 3^5
#I  Nuclear rank: 5
#I  3-multiplicator rank: 5
#I  # of immediate descendants of order 3^6 is 11
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 3^7 is 58
#I  # of capable immediate descendants is 32
#I  # of immediate descendants of order 3^8 is 58
#I  # of capable immediate descendants is 58
#I  # of immediate descendants of order 3^9 is 11
#I  # of capable immediate descendants is 11
#I  # of immediate descendants of order 3^10 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
148

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-PG-x-1-i.tst", 1 );
