# Generated by tst/make_example_tests.g from examples/3gp-SP-2-Rel-i
gap> START_TEST( "3gp-SP-2-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("x", "y");
<free group on the generators [ x, y ]>
gap> rels := ["(x * y * x)^3", "[y, x, x]"];
[ "(x * y * x)^3", "[y, x, x]" ]
gap> procId := PqStart(F : Prime := 3, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[2,0],
>                                     [0,2]],
> 
>                                    [[0,2],
>                                     [1,0]],
> 
>                                    [[1,2],
>                                     [2,2]],
> 
>                                    [[1,0],
>                                     [2,1]],
> 
>                                    [[2,0],
>                                     [0,1]] ]
> 
>                          : # options
>                            ClassBound := 9,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-SP-2-Rel-i.tst", 1 );
