# Generated by tst/make_example_tests.g from examples/3gp-maxoccur-Rel-i
gap> START_TEST( "3gp-maxoccur-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId", "class" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^3", "b^3"];
[ "a^3", "b^3" ]
gap> procId := PqStart(F : Prime := 3, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
gap> PqSetMaximalOccurrences(procId, [6, 4]);;
gap> for class in [2 .. 9] do
>   PqNextClass(procId);
> od;
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^3
#I  Group: [grp] to lower exponent-3 central class 3 has order 3^5
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
#I  Group: [grp] to lower exponent-3 central class 5 has order 3^11
#I  Group: [grp] to lower exponent-3 central class 6 has order 3^15
#I  Group: [grp] to lower exponent-3 central class 7 has order 3^23
#I  Group: [grp] to lower exponent-3 central class 8 has order 3^29
#I  Group: [grp] to lower exponent-3 central class 9 has order 3^35
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-maxoccur-Rel-i.tst", 1 );
