# Generated by tst/make_example_tests.g from examples/3gp-PG-4-i
gap> START_TEST( "3gp-PG-4-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> procId := PqStart(F : Prime := 3);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^4
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^14
gap> PqPGSupplyAutomorphisms(procId, [ [[2,0,0,0],
>                                    [0,1,0,0],
>                                    [0,0,1,0],
>                                    [0,0,0,1]],
> 
>                                   [[2,0,0,1],
>                                    [2,0,0,0],
>                                    [0,2,0,0],
>                                    [0,0,2,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 2,
>                                   OrderBound := 5);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 3^4
#I  Nuclear rank: 10
#I  3-multiplicator rank: 10
#I  # of immediate descendants of order 3^5 is 6
#I  # of capable immediate descendants is 2
#I  **************************************************
6

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-PG-4-i.tst", 1 );
