# Generated by tst/make_example_tests.g from examples/3gp-PG-i
gap> START_TEST( "3gp-PG-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 3);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^5
gap> PqPGSupplyAutomorphisms(procId, [ [[2,0],
>                                    [0,2]],
> 
>                                   [[0,2],
>                                    [1,0]],
> 
>                                   [[1,2],
>                                    [2,2]],
> 
>                                   [[1,0],
>                                    [2,1]],
> 
>                                   [[2,0],
>                                    [0,1]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 4,
>                                   CapableDescendants,
>                                   StepSize := [2, 3, 1],
>                                   PcgsAutomorphisms,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 3^2
#I  Nuclear rank: 3
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^4 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #1;2
#I  Order: 3^4
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  Group [grp] #1;2 is an invalid starting group
#I  **************************************************
#I  Starting group: [grp] #2;2
#I  Order: 3^4
#I  Nuclear rank: 3
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^7 is 4
#I  # of capable immediate descendants is 4
#I  **************************************************
#I  Starting group: [grp] #3;2
#I  Order: 3^4
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  Group [grp] #3;2 is an invalid starting group
#I  **************************************************
#I  **************************************************
#I  Starting group: [grp] #2;2 #1;3
#I  Order: 3^7
#I  Nuclear rank: 4
#I  3-multiplicator rank: 5
#I  # of immediate descendants of order 3^8 is 16
#I  # of capable immediate descendants is 11
#I  **************************************************
#I  Starting group: [grp] #2;2 #2;3
#I  Order: 3^7
#I  Nuclear rank: 3
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^8 is 13
#I  # of capable immediate descendants is 9
#I  **************************************************
#I  Starting group: [grp] #2;2 #3;3
#I  Order: 3^7
#I  Nuclear rank: 3
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^8 is 13
#I  # of capable immediate descendants is 9
#I  **************************************************
#I  Starting group: [grp] #2;2 #4;3
#I  Order: 3^7
#I  Nuclear rank: 3
#I  3-multiplicator rank: 4
#I  # of immediate descendants of order 3^8 is 7
#I  # of capable immediate descendants is 5
#I  **************************************************
41

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-PG-i.tst", 1 );
