# Generated by tst/make_example_tests.g from examples/3gp-a-Rel
gap> START_TEST( "3gp-a-Rel.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^3", "b^3"];
[ "a^3", "b^3" ]
gap> Pq( F : Prime := 3, Exponent := 9, Relators := rels, ClassBound := 6,
>         OutputLevel := 1 );
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^3
#I  Group: [grp] to lower exponent-3 central class 3 has order 3^5
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
#I  Group: [grp] to lower exponent-3 central class 5 has order 3^9
#I  Group: [grp] to lower exponent-3 central class 6 has order 3^11
<pc group of size 177147 with 11 generators>

# interactive form: PqExample( "3gp-a-Rel", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^3", "b^3"];
[ "a^3", "b^3" ]
gap> procId := PqStart( F );
1
gap> Pq( procId : Prime := 3, Exponent := 9, Relators := rels, ClassBound := 6,
>         OutputLevel := 1 );
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^3
#I  Group: [grp] to lower exponent-3 central class 3 has order 3^5
#I  Group: [grp] to lower exponent-3 central class 4 has order 3^7
#I  Group: [grp] to lower exponent-3 central class 5 has order 3^9
#I  Group: [grp] to lower exponent-3 central class 6 has order 3^11
<pc group of size 177147 with 11 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-a-Rel.tst", 1 );
