# Generated by tst/make_example_tests.g from examples/3gp-PG-x-i
gap> START_TEST( "3gp-PG-x-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 3);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-3 central series for [grp]
#I  Group: [grp] to lower exponent-3 central class 1 has order 3^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-3 central class 2 has order 3^5
gap> PqPGSupplyAutomorphisms(procId, [ [[1,1],
>                                    [0,1]],
> 
>                                   [[0,1],
>                                    [1,0]] ]);;
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 
#I  Generator  4 --> 0 0 0 1 1 
#I  Generator  5 --> 0 0 0 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 0 1 0 0 0 
#I  Generator  2 --> 1 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 
#I  Generator  4 --> 0 0 0 0 1 
#I  Generator  5 --> 0 0 0 1 0 
gap> PqPGConstructDescendants(procId : ClassBound := 2,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 3^2
#I  Nuclear rank: 3
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^3 is 3
#I  # of capable immediate descendants is 2
#I  # of immediate descendants of order 3^4 is 3
#I  # of capable immediate descendants is 3
#I  # of immediate descendants of order 3^5 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
6
gap> PqPGSetDescendantToPcp(procId, 2, 5);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 1 0 0 
#I  Generator  4 --> 0 0 0 1 0 1 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 2 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 0 1 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 1 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 3,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2
#I  Order: 3^4
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^5 is 2
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 3^6 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
2
gap> PqPGSetDescendantToPcp(procId, 3, 2);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 1 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 1 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 
#I  Generator  9 --> 0 0 0 0 0 0 2 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 1 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 1 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 2 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 2 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 1 1 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 4,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;2
#I  Order: 3^6
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^7 is 2
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 3^8 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
2
gap> PqPGSetDescendantToPcp(procId, 4, 2);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 0 0 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 1 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 1 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 2 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 1 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 1 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 2 0 0 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 2 0 1 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 1 1 2 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 1 1 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 2 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 5,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;2 #3;2
#I  Order: 3^8
#I  Nuclear rank: 2
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^9 is 2
#I  # of capable immediate descendants is 1
#I  # of immediate descendants of order 3^10 is 1
#I  # of capable immediate descendants is 1
#I  **************************************************
2
gap> PqPGSetDescendantToPcp(procId, 5, 1);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 1 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 1 0 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 1 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 1 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 1 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 2 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 2 0 0 0 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 2 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 1 1 0 0 2 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 1 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 5:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 2 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 6,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;2 #3;2 #1;1
#I  Order: 3^9
#I  Nuclear rank: 1
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^10 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
1
gap> PqPGSetDescendantToPcp(procId, 6, 1);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 1 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 1 0 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 1 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 1 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 1 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 1 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 1 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 1 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 2 1 
#I  Automorphism 5:
#I  Generator  1 --> 1 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 2 0 0 0 0 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 2 0 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 1 1 0 0 0 2 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 1 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 6:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 2 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 7,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;2 #3;2 #1;1 #1;1
#I  Order: 3^10
#I  Nuclear rank: 1
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^11 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
1
gap> PqPGSetDescendantToPcp(procId, 7, 1);
gap> PqPGExtendAutomorphisms(procId);;
#I  Automorphism 1:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 1 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 2:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 1 
#I  Automorphism 3:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 1 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 1 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 4:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 1 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 1 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 1 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 5:
#I  Generator  1 --> 1 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 1 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 1 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 1 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 1 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 2 1 
#I  Automorphism 6:
#I  Generator  1 --> 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 1 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 1 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 1 1 2 0 2 0 0 0 0 0 0 1 
#I  Generator  5 --> 0 0 0 0 1 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 1 1 2 0 0 0 0 0 1 0 
#I  Generator  7 --> 0 0 0 0 0 0 1 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 1 1 0 0 0 0 2 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 1 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 0 1 
#I  Automorphism 7:
#I  Generator  1 --> 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  2 --> 0 2 0 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  3 --> 0 0 2 0 0 0 0 0 0 0 0 0 0 0 
#I  Generator  4 --> 0 0 0 1 0 0 0 0 0 0 0 0 0 0 
#I  Generator  5 --> 0 0 0 0 2 0 0 0 0 0 0 0 0 0 
#I  Generator  6 --> 0 0 0 0 0 1 0 0 0 0 0 0 0 0 
#I  Generator  7 --> 0 0 0 0 0 0 2 0 0 0 0 0 0 0 
#I  Generator  8 --> 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
#I  Generator  9 --> 0 0 0 0 0 0 0 0 1 0 0 0 0 0 
#I  Generator 10 --> 0 0 0 0 0 0 0 0 0 1 0 0 0 0 
#I  Generator 11 --> 0 0 0 0 0 0 0 0 0 0 1 0 0 0 
#I  Generator 12 --> 0 0 0 0 0 0 0 0 0 0 0 1 0 0 
#I  Generator 13 --> 0 0 0 0 0 0 0 0 0 0 0 0 2 0 
#I  Generator 14 --> 0 0 0 0 0 0 0 0 0 0 0 0 0 2 
gap> PqPGConstructDescendants(procId : ClassBound := 8,
>                                   CapableDescendants,
>                                   BasicAlgorithm);
#I  **************************************************
#I  Starting group: [grp] #6;2 #3;2 #3;2 #1;1 #1;1 #1;1
#I  Order: 3^11
#I  Nuclear rank: 1
#I  3-multiplicator rank: 3
#I  # of immediate descendants of order 3^12 is 2
#I  # of capable immediate descendants is 1
#I  **************************************************
1

#
gap> PqQuitAll();
gap> STOP_TEST( "3gp-PG-x-i.tst", 1 );
