# Generated by tst/make_example_tests.g from examples/5gp-c-Rel-i
gap> START_TEST( "5gp-c-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> rels := ["[a, b, b, c]", "(a * b * c^d * a)^25", 
>          "(a * b)^25 * [a, c, c, d]^-2"];
[ "[a, b, b, c]", "(a * b * c^d * a)^25", "(a * b)^25 * [a, c, c, d]^-2" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 2, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^4
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^14

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-c-Rel-i.tst", 1 );
