# Generated by tst/make_example_tests.g from examples/5gp-SP-d-Rel-i
gap> START_TEST( "5gp-SP-d-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^25", "[b, a, a, a, b]", "[b, a, b, b, b]",
>          "[b, a, b, a]", "b^5 * [a, b, a]^-1"];
[ "a^25", "[b, a, a, a, b]", "[b, a, b, b, b]", "[b, a, b, a]", 
  "b^5 * [a, b, a]^-1" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 2);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,1],
>                                     [0,1,0,0]],
> 
>                                    [[1,0,0,0],
>                                     [0,1,0,1]],
> 
>                                    [[1,3,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[1,3,0,0],
>                                     [0,4,0,0]],
> 
>                                    [[1,2,0,0],
>                                     [0,3,0,0]],
> 
>                                    [[4,0,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[3,0,0,0],
>                                     [0,1,0,0]] ]
> 
>                          : # options
>                            ClassBound := 20,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-SP-d-Rel-i.tst", 1 );
