# Generated by tst/make_example_tests.g from examples/5gp-Rel-i
gap> START_TEST( "5gp-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c");
<free group on the generators [ a, b, c ]>
gap> rels := ["a^25 * c", "[a,  b] * c^-4", "[a, c]^25"];
[ "a^25 * c", "[a,  b] * c^-4", "[a, c]^25" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 27, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^4
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^6
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^12
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^14
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^16
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^20
#I  Group: [grp] to lower exponent-5 central class 11 has order 5^22
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^24
#I  Group: [grp] to lower exponent-5 central class 13 has order 5^26
#I  Group: [grp] to lower exponent-5 central class 14 has order 5^28
#I  Group: [grp] to lower exponent-5 central class 15 has order 5^30
#I  Group: [grp] to lower exponent-5 central class 16 has order 5^32
#I  Group: [grp] to lower exponent-5 central class 17 has order 5^34
#I  Group: [grp] to lower exponent-5 central class 18 has order 5^36
#I  Group: [grp] to lower exponent-5 central class 19 has order 5^38
#I  Group: [grp] to lower exponent-5 central class 20 has order 5^40
#I  Group: [grp] to lower exponent-5 central class 21 has order 5^42
#I  Group: [grp] to lower exponent-5 central class 22 has order 5^44
#I  Group: [grp] to lower exponent-5 central class 23 has order 5^46
#I  Group: [grp] to lower exponent-5 central class 24 has order 5^48
#I  Group: [grp] to lower exponent-5 central class 25 has order 5^50
#I  Group: [grp] to lower exponent-5 central class 26 has order 5^52
#I  Group: [grp] to lower exponent-5 central class 27 has order 5^54
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-Rel-i.tst", 1 );
