# Generated by tst/make_example_tests.g from examples/5gp-b-Rel-i
gap> START_TEST( "5gp-b-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("x", "y", "z", "w");
<free group on the generators [ x, y, z, w ]>
gap> rels := ["x^25 * (x^z)^-1", "[x, y] * z^-1", "[x, z]"];
[ "x^25 * (x^z)^-1", "[x, y] * z^-1", "[x, z]" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 5, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^32

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-b-Rel-i.tst", 1 );
