# Generated by tst/make_example_tests.g from examples/5gp-maxoccur-Rel-i
gap> START_TEST( "5gp-maxoccur-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId", "class" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^5", "b^5"];
[ "a^5", "b^5" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
gap> PqSetMaximalOccurrences(procId, [3, 2]);;
gap> for class in [2 .. 6] do
>   PqNextClass(procId);
> od;
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^7
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^9
#I  Group completed. Lower exponent-5 central class = 5, Order = 5^9
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^9
gap> PqDisplayPcPresentation(procId);;
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^9
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-maxoccur-Rel-i.tst", 1 );
