# Generated by tst/make_example_tests.g from examples/5gp-a-Rel-i
gap> START_TEST( "5gp-a-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^5", "b^5", "(a * b)^5", "(a * b^2)^5", "(a * b^-2)^5",
>          "(a * b^-1)^5", "(a^2 * b)^5", "(a^2 * b^2)^5", "(a^2 * b^-2)^5",
>          "(a^2 * b^-1)^5", "(a * b * a^-1 * b^2)^5", 
>          "(a * b * a^2 * b^-1)^5", "(a * b * a^2 * b^2)^5",
>          "(a * b * a * b^-1)^5", "(a * b * a^-1 * b)^5",
>          "(a * b * a^-1 * b^-1)^5"];
[ "a^5", "b^5", "(a * b)^5", "(a * b^2)^5", "(a * b^-2)^5", "(a * b^-1)^5", 
  "(a^2 * b)^5", "(a^2 * b^2)^5", "(a^2 * b^-2)^5", "(a^2 * b^-1)^5", 
  "(a * b * a^-1 * b^2)^5", "(a * b * a^2 * b^-1)^5", "(a * b * a^2 * b^2)^5",
  "(a * b * a * b^-1)^5", "(a * b * a^-1 * b)^5", "(a * b * a^-1 * b^-1)^5" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 5, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
gap> PqNextClass(procId);; #class 6
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^14
gap> PqNextClass(procId);; #class 7
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^18
gap> PqNextClass(procId);; #class 8
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^22
gap> PqNextClass(procId);; #class 9
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^28
gap> PqNextClass(procId);; #class 10
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^39
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-a-Rel-i.tst", 1 );
