# Generated by tst/make_example_tests.g from examples/5gp-PG-i
gap> START_TEST( "5gp-PG-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 5);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^5
gap> PqPGSupplyAutomorphisms(procId, [ [[2,0],
>                                    [0,1]],
> 
>                                   [[4,1],
>                                    [4,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 2,
>                                   StepSize := 2,
>                                   RankInitialSegmentSubgroups := 4);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 5^2
#I  Nuclear rank: 3
#I  5-multiplicator rank: 3
#I  # of immediate descendants of order 5^4 is 3
#I  # of capable immediate descendants is 3
#I  **************************************************
3

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-PG-i.tst", 1 );
