# Generated by tst/make_example_tests.g from examples/5gp-SP-big-Rel-i
gap> START_TEST( "5gp-SP-big-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> rels := ["a * b^d", "c * d^a", "[c, a, a]", "[c, b, b, a]"];
[ "a * b^d", "c * d^a", "[c, a, a]", "[c, b, b, a]" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[4,1],
>                                     [4,0]],
> 
>                                    [[2,0],
>                                     [0,1]] ]
> 
>                          : # options
>                            ClassBound := 5);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-SP-big-Rel-i.tst", 1 );
