# Generated by tst/make_example_tests.g from examples/5gp-metabelian-Rel-i
gap> START_TEST( "5gp-metabelian-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId", "class" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^625", "b^625", "[b, a, b]", "[b, a, a, a, a] * [b, a]^-5"];
[ "a^625", "b^625", "[b, a, b]", "[b, a, a, a, a] * [b, a]^-5" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
gap> PqSetMetabelian(procId);
gap> for class in [2 .. 14] do
>   PqNextClass(procId);
> od;
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^11
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^12
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^13
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^14
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^15
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^16
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^17
#I  Group: [grp] to lower exponent-5 central class 11 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^19
#I  Group: [grp] to lower exponent-5 central class 13 has order 5^20
#I  Group completed. Lower exponent-5 central class = 13, Order = 5^20
#I  Group: [grp] to lower exponent-5 central class 13 has order 5^20
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "5gp-metabelian-Rel-i.tst", 1 );
