# Generated by tst/make_example_tests.g from examples/7gp-Rel-i
gap> START_TEST( "7gp-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["[b, a, a, b, b]^49", "(a * b * b * a * b * a)^49", "b^7"];
[ "[b, a, a, b, b]^49", "(a * b * b * a * b * a)^49", "b^7" ]
gap> procId := PqStart(F : Prime := 7, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 10, 
>                           OutputLevel := 1);;
#I  Lower exponent-7 central series for [grp]
#I  Group: [grp] to lower exponent-7 central class 1 has order 7^2
#I  Group: [grp] to lower exponent-7 central class 2 has order 7^4
#I  Group: [grp] to lower exponent-7 central class 3 has order 7^6
#I  Group: [grp] to lower exponent-7 central class 4 has order 7^9
#I  Group: [grp] to lower exponent-7 central class 5 has order 7^15
#I  Group: [grp] to lower exponent-7 central class 6 has order 7^24
#I  Group: [grp] to lower exponent-7 central class 7 has order 7^42
#I  Group: [grp] to lower exponent-7 central class 8 has order 7^72
#I  Group: [grp] to lower exponent-7 central class 9 has order 7^128
#I  Group: [grp] to lower exponent-7 central class 10 has order 7^226
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "7gp-Rel-i.tst", 1 );
