# Generated by tst/make_example_tests.g from examples/7gp-SP-b-Rel-i
gap> START_TEST( "7gp-SP-b-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["b^7 * [b, a, a]^-1", "[b, a, b]"];
[ "b^7 * [b, a, a]^-1", "[b, a, b]" ]
gap> procId := PqStart(F : Prime := 7, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 2);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,1],
>                                     [0,1,0,0]],
> 
>                                    [[1,0,0,0],
>                                     [0,1,0,1]],
> 
>                                    [[1,3,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[6,0,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[3,0,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[1,2,0,0],
>                                     [0,6,0,0]],
> 
>                                    [[1,4,0,0],
>                                     [0,4,0,0]] ]
> 
>                          : # options
>                            ClassBound := 40,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "7gp-SP-b-Rel-i.tst", 1 );
