# Generated by tst/make_example_tests.g from examples/7gp-PG-i
gap> START_TEST( "7gp-PG-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 7);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-7 central series for [grp]
#I  Group: [grp] to lower exponent-7 central class 1 has order 7^2
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-7 central class 2 has order 7^5
gap> PqPGSupplyAutomorphisms(procId, [ [[3,0],
>                                    [0,1]],
> 
>                                   [[6,1],
>                                    [6,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 2,
>                                   CapableDescendants,
>                                   StepSize := 1);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 7^2
#I  Nuclear rank: 3
#I  7-multiplicator rank: 3
#I  # of immediate descendants of order 7^3 is 3
#I  # of capable immediate descendants is 2
#I  **************************************************
2

#
gap> PqQuitAll();
gap> STOP_TEST( "7gp-PG-i.tst", 1 );
