# Generated by tst/make_example_tests.g from examples/B2-4
gap> START_TEST( "B2-4.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> Pq( F : Prime := 2, Exponent := 4 );
<pc group of size 4096 with 12 generators>

# interactive form: PqExample( "B2-4", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart( F );
1
gap> Pq( procId : Prime := 2, Exponent := 4 );
<pc group of size 4096 with 12 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "B2-4.tst", 1 );
