# Generated by tst/make_example_tests.g from examples/B2-4-SP-i
gap> START_TEST( "B2-4-SP-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b"); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> procId := PqStart(F : Prime := 2, Exponent := 4);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[0,1],
>                                     [1,1]],
> 
>                                    [[0,1],
>                                     [1,0]] ]
> 
>                          : # options
>                            ClassBound := 6,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "B2-4-SP-i.tst", 1 );
