# Generated by tst/make_example_tests.g from examples/B2-5
gap> START_TEST( "B2-5.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> Pq( F : Prime := 5, ClassBound := 14, Exponent := 5,
>         OutputLevel := 1 );
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^14
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^22
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^28
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^31
#I  Group: [grp] to lower exponent-5 central class 11 has order 5^33
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^34
#I  Group completed. Lower exponent-5 central class = 12, Order = 5^34
<pc group of size 582076609134674072265625 with 34 generators>

# interactive form: PqExample( "B2-5", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart( F );
1
gap> Pq( procId : Prime := 5, ClassBound := 14, Exponent := 5,
>         OutputLevel := 1 );
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^14
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^22
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^28
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^31
#I  Group: [grp] to lower exponent-5 central class 11 has order 5^33
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^34
#I  Group completed. Lower exponent-5 central class = 12, Order = 5^34
<pc group of size 582076609134674072265625 with 34 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "B2-5.tst", 1 );
