# Generated by tst/make_example_tests.g from examples/B2-8-i
gap> START_TEST( "B2-8-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 2, Exponent := 8);;
gap> PqPcPresentation(procId : ClassBound := 10, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^2
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^5
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^10
#I  Group: [grp] to lower exponent-2 central class 4 has order 2^15
#I  Group: [grp] to lower exponent-2 central class 5 has order 2^24
#I  Group: [grp] to lower exponent-2 central class 6 has order 2^35
#I  Group: [grp] to lower exponent-2 central class 7 has order 2^53
#I  Group: [grp] to lower exponent-2 central class 8 has order 2^83
#I  Group: [grp] to lower exponent-2 central class 9 has order 2^139
#I  Group: [grp] to lower exponent-2 central class 10 has order 2^238
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "B2-8-i.tst", 1 );
