# Generated by tst/make_example_tests.g from examples/B4-4-i
gap> START_TEST( "B4-4-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "class" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b", "c", "d");
<free group on the generators [ a, b, c, d ]>
gap> procId := PqStart(F : Prime := 2, Exponent := 4);;
gap> PqPcPresentation(procId : ClassBound := 6, 
>                           OutputLevel := 1);;
#I  Lower exponent-2 central series for [grp]
#I  Group: [grp] to lower exponent-2 central class 1 has order 2^4
#I  Group: [grp] to lower exponent-2 central class 2 has order 2^14
#I  Group: [grp] to lower exponent-2 central class 3 has order 2^34
#I  Group: [grp] to lower exponent-2 central class 4 has order 2^89
#I  Group: [grp] to lower exponent-2 central class 5 has order 2^188
#I  Group: [grp] to lower exponent-2 central class 6 has order 2^272
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "B4-4-i.tst", 1 );
