# Generated by tst/make_example_tests.g from examples/B5-4.g
gap> START_TEST( "B5-4.g.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "procId", "Relations", "class", "w", "smallclass" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> LoadPackage( "anupq" );
true
gap> #You might like to try setting: `SetInfoLevel( InfoANUPQ, 3 );'
gap> procId := PqStart( FreeGroup(5) : Exponent := 4, Prime := 2 );;
gap> Pq( procId : ClassBound := 2 );
<pc group of size 1048576 with 20 generators>
gap> PqSupplyAutomorphisms( procId,
>       [
>         [ [ 1, 1, 0, 0, 0],      #1st automorphism
>           [ 0, 1, 0, 0, 0],
>           [ 0, 0, 1, 0, 0],
>           [ 0, 0, 0, 1, 0],
>           [ 0, 0, 0, 0, 1] ],
> 
>         [ [ 0, 0, 0, 0, 1],      #2nd automorphism
>           [ 1, 0, 0, 0, 0],
>           [ 0, 1, 0, 0, 0],
>           [ 0, 0, 1, 0, 0],
>           [ 0, 0, 0, 1, 0] ]
>                              ] );;
gap> Relations :=
>   [ [],          ## class 1
>     [],          ## class 2
>     [],          ## class 3
>     [],          ## class 4
>     [],          ## class 5
>     [],          ## class 6
>     ## class 7     
>     [ [ "x2","x1","x1","x3","x4","x4","x4" ] ],
>     ## class 8
>     [ [ "x2","x1","x1","x3","x4","x5","x5","x5" ] ],
>     ## class 9
>     [ [ "x2","x1","x1","x3","x4","x4","x5","x5","x5" ],
>       [ "x2","x1","x1","x2","x3","x4","x5","x5","x5" ],
>       [ "x2","x1","x1","x3","x3","x4","x5","x5","x5" ] ],
>     ## class 10
>     [ [ "x2","x1","x1","x2","x3","x3","x4","x5","x5","x5" ],
>       [ "x2","x1","x1","x3","x3","x4","x4","x5","x5","x5" ] ],
>     ## class 11
>     [ [ "x2","x1","x1","x2","x3","x3","x4","x4","x5","x5","x5" ],
>       [ "x2","x1","x1","x2","x3","x1","x3","x4","x2","x4","x3" ] ],
>     ## class 12
>     [ [ "x2","x1","x1","x2","x3","x1","x3","x4","x2","x5","x5","x5" ],
>       [ "x2","x1","x1","x3","x2","x4","x3","x5","x4","x5","x5","x5" ] ],
>     ## class 13
>     [ [ "x2","x1","x1","x2","x3","x1","x3","x4","x2","x4","x5","x5","x5" 
>         ] ]
> ];
[ [  ], [  ], [  ], [  ], [  ], [  ], 
  [ [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ] ], 
  [ [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ] ], 
  [ [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ], 
      [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ], 
      [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ] ], 
  [ [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x5", "x5", "x5" ], 
      [ "x2", "x1", "x1", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ] ], 
  [ [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ], 
      [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", "x3" ] ], 
  [ [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x5", "x5", "x5" ]
        , [ "x2", "x1", "x1", "x3", "x2", "x4", "x3", "x5", "x4", "x5", "x5", 
          "x5" ] ], 
  [ [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", "x5", "x5", 
          "x5" ] ] ]
gap> for class in [ 3 .. 13 ] do
>     Print( "Computing class ", class, "\n" );
>     PqSetupTablesForNextClass( procId );
> 
>     for w in [ class, class-1 .. 7 ] do
> 
>         PqAddTails( procId, w );   
>         PqDisplayPcPresentation( procId );
> 
>         if Relations[ w ] <> [] then
>             # recalculate automorphisms
>             PqExtendAutomorphisms( procId );
> 
>             for r in Relations[ w ] do
>                 Print( "Collecting ", r, "\n" );
>                 PqCommutator( procId, r, 1 );
>                 PqEchelonise( procId );
>                 PqApplyAutomorphisms( procId, 15 ); #queue factor = 15
>             od;
> 
>             PqEliminateRedundantGenerators( procId );
>         fi;   
>         PqComputeTails( procId, w );
>     od;
>     PqDisplayPcPresentation( procId );
> 
>     smallclass := Minimum( class, 6 );
>     for w in [ smallclass, smallclass-1 .. 2 ] do
>         PqTails( procId, w );
>     od;
>     # recalculate automorphisms
>     PqExtendAutomorphisms( procId );
>     PqCollect( procId, "x5^4" );
>     PqEchelonise( procId );
>     PqApplyAutomorphisms( procId, 15 ); #queue factor = 15
>     PqEliminateRedundantGenerators( procId );
>     PqDisplayPcPresentation( procId );
> od;
Computing class 3
Computing class 4
Computing class 5
Computing class 6
Computing class 7
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 8
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 9
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 10
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 11
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x4", "x5", "x5", "x5" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", "x3" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 12
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x5", 
  "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x2", "x4", "x3", "x5", "x4", "x5", 
  "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x4", "x5", "x5", "x5" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", "x3" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
Computing class 13
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", 
  "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x5", 
  "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x2", "x4", "x3", "x5", "x4", "x5", 
  "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x4", "x5", "x5", "x5" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x1", "x3", "x4", "x2", "x4", "x3" 
 ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x2", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x5", "x5", "x5" ]
Collecting [ "x2", "x1", "x1", "x3", "x4", "x4", "x4" ]
gap> PqWritePcPresentation( procId, "/tmp/B54" );;
gap> PqQuit( procId );;

#
gap> PqQuitAll();
gap> STOP_TEST( "B5-4.g.tst", 1 );
