# Generated by tst/make_example_tests.g from examples/B5-5-Engel3-Id
gap> START_TEST( "B5-5-Engel3-Id.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "B5-5-Engel3-Id", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "Burnside5", "Engel3", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup(2);
<free group on the generators [ f1, f2 ]>
gap> Burnside5 := x->x^5;
function( x ) ... end
gap> Engel3 := function( x,y ) return PqLeftNormComm( [x,y,y,y] ); end;
function( x, y ) ... end
gap> procId := PqStart( F );
1
gap> Pq( procId : Prime := 5, Identities := [ Burnside5, Engel3 ] );
#I  Class 1 with 2 generators.
#I  Class 2 with 3 generators.
#I  Class 3 with 5 generators.
#I  Class 3 with 5 generators.
<pc group of size 3125 with 5 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "B5-5-Engel3-Id.tst", 1 );
