# Generated by tst/make_example_tests.g from examples/F2-5-i
gap> START_TEST( "F2-5-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 5);;
gap> PqPcPresentation(procId : ClassBound := 6, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^32
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^55
gap> PqNextClass(procId);; #class 7
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^96
gap> PqNextClass(procId);; #class 8
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^167
gap> PqNextClass(procId);; #class 9
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^294

#
gap> PqQuitAll();
gap> STOP_TEST( "F2-5-i.tst", 1 );
