# Generated by tst/make_example_tests.g from examples/gp-256-SP-Rel-i
gap> START_TEST( "gp-256-SP-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^4 * [b, a, a, a, a, a]^-1", 
>          "b * a^2 * b^-1 * a^-2 * [b, a, a, a, a, a]^-1", 
>          "b^2 * [b, a, a, a, a, a]^-1" ];
[ "a^4 * [b, a, a, a, a, a]^-1", 
  "b * a^2 * b^-1 * a^-2 * [b, a, a, a, a, a]^-1", 
  "b^2 * [b, a, a, a, a, a]^-1" ]
gap> procId := PqStart(F : Prime := 2, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 1);;
gap> PqSPStandardPresentation(procId, [ [[0,1],
>                                     [1,1]],
> 
>                                    [[0,1],
>                                     [1,0]] ]
> 
>                          : # options
>                            ClassBound := 8,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "gp-256-SP-Rel-i.tst", 1 );
