# Generated by tst/make_example_tests.g from examples/Nott-PG-Rel-i
gap> START_TEST( "Nott-PG-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^5", "b^5", "[b, a, b]"];
[ "a^5", "b^5", "[b, a, b]" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 3, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^4
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;
gap> PqPGSupplyAutomorphisms(procId, [ [[1,0,0,0],
>                                    [0,1,0,1]],
> 
>                                   [[1,1,0,0],
>                                    [0,1,0,1]],
> 
>                                   [[1,0,0,0],
>                                    [0,4,0,0]],
> 
>                                   [[1,0,0,0],
>                                    [0,2,0,0]],
> 
>                                   [[4,0,0,0],
>                                    [0,1,0,0]],
> 
>                                   [[2,0,0,0],
>                                    [0,1,0,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 4,
>                                   CapableDescendants,
>                                   StepSize := 1,
>                                   PcgsAutomorphisms,
>                                   RankInitialSegmentSubgroups := 4);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 5^4
#I  Nuclear rank: 1
#I  5-multiplicator rank: 4
#I  # of immediate descendants of order 5^5 is 9
#I  # of capable immediate descendants is 2
#I  **************************************************
2

#
gap> PqQuitAll();
gap> STOP_TEST( "Nott-PG-Rel-i.tst", 1 );
