# Generated by tst/make_example_tests.g from examples/Nott-APG-Rel-i
gap> START_TEST( "Nott-APG-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^5", "b^5", "[b, a, b]"];
[ "a^5", "b^5", "[b, a, b]" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqPcPresentation(procId : ClassBound := 3, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^4
gap> PqComputePCover(procId);;
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;
gap> PqPGSupplyAutomorphisms(procId, [ [[1,0,0,0],
>                                    [0,1,0,1]],
> 
>                                   [[1,1,0,0],
>                                    [0,1,0,1]],
> 
>                                   [[1,0,0,0],
>                                    [0,4,0,0]],
> 
>                                   [[1,0,0,0],
>                                    [0,2,0,0]],
> 
>                                   [[4,0,0,0],
>                                    [0,1,0,0]],
> 
>                                   [[2,0,0,0],
>                                    [0,1,0,0]] ]);;
gap> PqPGConstructDescendants(procId : ClassBound := 4,
>                                   CapableDescendants,
>                                   StepSize := 1,
>                                   PcgsAutomorphisms,
>                                   RankInitialSegmentSubgroups := 4);
#I  **************************************************
#I  Starting group: [grp]
#I  Order: 5^4
#I  Nuclear rank: 1
#I  5-multiplicator rank: 4
#I  # of immediate descendants of order 5^5 is 9
#I  # of capable immediate descendants is 2
#I  **************************************************
2
gap> PqPGSetDescendantToPcp(procId, 4, 1);;
gap> PqAPGDegree(procId, 2, 3);
#I  Degree of permutation group is 25
25
gap> PqAPGPermutations(procId);;
gap> PqAPGOrbits(procId : CustomiseOutput := rec(orbit := [1]));
#I    Orbit          Length      Representative
#I        1               5               1
#I        2              20               2
#I  Number of orbits is 2
2
gap> PqAPGOrbitRepresentatives(procId);;
gap> PqPGSetDescendantToPcp(procId);;
gap> PqDisplayPcPresentation(procId);;
#I  Group: [grp] #1;1 to lower exponent-5 central class 5 has order 5^9
#I  Class 1
#I  1 is defined on image of defining generator 1
#I  2 is defined on image of defining generator 2
#I  Class 2
#I  3 is defined on [2, 1] = 2 1 
#I  Class 3
#I  4 is defined on [3, 1] = 2 1 1 
#I  Class 4
#I  5 is defined on [4, 1] = 2 1 1 1 
#I  Class 5
#I  6 is defined on [5, 1] = 2 1 1 1 1 
#I  7 is defined on [5, 2] = 2 1 1 1 2 
#I  8 is defined on 1^5 = 1 1 
#I  9 is defined on 2^5 = 2 2 
#I  Non-trivial powers:
#I   .1^5 = .8
#I   .2^5 = .9
#I  Non-trivial commutators:
#I  [ .2, .1 ] = .3
#I  [ .3, .1 ] = .4
#I  [ .4, .1 ] = .5
#I  [ .4, .2 ] = .7
#I  [ .4, .3 ] = .7^4
#I  [ .5, .1 ] = .6
#I  [ .5, .2 ] = .7
gap> PqAPGSingleStage(procId : StepSize:=2, BasicAlgorithm, 
>                           CustomiseOutput := rec());;
#I  **************************************************
#I  Starting group: [grp] #1;1
#I  Order: 5^5
#I  Nuclear rank: 2
#I  5-multiplicator rank: 4
#I  # of immediate descendants of order 5^7 is 40
#I  # of capable immediate descendants is 5

#
gap> PqQuitAll();
gap> STOP_TEST( "Nott-APG-Rel-i.tst", 1 );
