# Generated by tst/make_example_tests.g from examples/Nott-SP-Rel-i
gap> START_TEST( "Nott-SP-Rel-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "rels", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := ["a^5", "b^5", "[b, a, b]"];
[ "a^5", "b^5", "[b, a, b]" ]
gap> procId := PqStart(F : Prime := 5, Relators := rels);;
gap> PqSPComputePcpAndPCover(procId : ClassBound := 3);;
gap> PqSPStandardPresentation(procId, [ [[1,0,0,0],
>                                     [0,1,0,1]],
> 
>                                    [[1,1,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[1,0,0,0],
>                                     [0,4,0,0]],
> 
>                                    [[1,0,0,0],
>                                     [0,2,0,0]],
> 
>                                    [[4,0,0,0],
>                                     [0,1,0,0]],
> 
>                                    [[2,0,0,0],
>                                     [0,1,0,0]] ]
> 
>                          : # options
>                            ClassBound := 10,
>                            PcgsAutomorphisms);;

#
gap> PqQuitAll();
gap> STOP_TEST( "Nott-SP-Rel-i.tst", 1 );
