# Generated by tst/make_example_tests.g from examples/Pq
gap> START_TEST( "Pq.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "Pq", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "procId1", "procId2", "procId3", "procId4", "G", "R", "H", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b"); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> procId1 := PqStart( F );
1
gap> Pq( procId1 : Prime := 2, ClassBound := 3 );
<pc group of size 1024 with 10 generators>
gap> # Now let us get a p-quotient of an fp group
gap> G := F / [a^4, b^4];
<fp group on the generators [ a, b ]>
gap> procId2 := PqStart( G );
2
gap> Pq( procId2 : Prime := 2, ClassBound := 3 );
<pc group of size 256 with 8 generators>
gap> # Now let's get a different p-quotient of the same group
gap> Pq( procId2 : Prime := 2, ClassBound := 3,
>               RedoPcp,
>               Exponent := 4 );
<pc group of size 128 with 7 generators>
gap> # Now we'll get a p-quotient of another fp group
gap> # which we will redo using the `Relators' option
gap> R := [ a^25, Comm(Comm(b, a), a), b^5 ];
[ a^25, a^-1*b^-1*a*b*a^-1*b^-1*a^-1*b*a^2, b^5 ]
gap> H := F / R;
<fp group on the generators [ a, b ]>
gap> procId3 := PqStart( H );
3
gap> Pq( procId3 : Prime := 5, ClassBound := 5, Metabelian );
<pc group of size 78125 with 7 generators>
gap> # Now we redo the previous example using the `Relators' option
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> # `F' was defined for `Relators'. We use the same strings that GAP uses
gap> # for printing the free group generators. It is *not* necessary to
gap> # predefine: a := F.1; etc. (as it was above).
gap> rels := [ "a^25", "[b, a, a]", "b^5" ];
[ "a^25", "[b, a, a]", "b^5" ]
gap> R := PqGAPRelators(F, rels);
[ a^25, a^-1*b^-1*a*b*a^-1*b^-1*a^-1*b*a^2, b^5 ]
gap> H := F / R;
<fp group on the generators [ a, b ]>
gap> Pq( procId3 : Prime := 5, ClassBound := 5, Metabelian, 
>               RedoPcp,
>               Relators := rels );
<pc group of size 78125 with 7 generators>
gap> # Above we could have just passed `F' (rather than `H'):
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := [ "a^25", "[b, a, a]", "b^5" ];
[ "a^25", "[b, a, a]", "b^5" ]
gap> procId4 := PqStart( F );
4
gap> Pq( procId4 : Prime := 5, ClassBound := 5, Metabelian, 
>         Relators := rels );
<pc group of size 78125 with 7 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "Pq.tst", 1 );
