# Generated by tst/make_example_tests.g from examples/PqDescendantsTreeCoclassOne-9-i
gap> START_TEST( "PqDescendantsTreeCoclassOne-9-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "G", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> G := ElementaryAbelianGroup( 9 );
<pc group of size 9 with 2 generators>
gap> procId := PqStart( G );;
gap> PqDescendantsTreeCoclassOne( procId : TreeDepth := 5 );;
#I  Number of descendants of group #1;1 to class 2: 2
#I  Number of descendants of group #1;1 #1;1 to class 3: 2
#I  Number of descendants of group #1;1 #1;1 #1;1 to class 4: 2
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 to class 5: 2
#I  group restored from file is incapable
#I  Number of descendants of group #1;1 #1;1 #1;1 #2;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #1;1 #1;1 #2;1 to class 4: 0
#I  group restored from file is incapable
#I  Number of descendants of group #1;1 #2;1 to class 3: 0
#I  Number of descendants of group #2;1 to class 2: 4
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #1;1 to class 3: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #2;1 to class 3: 0
#I  Number of descendants of group #2;1 #3;1 to class 3: 6
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #1;1 to class 4: 0
#I  Number of descendants of group #2;1 #3;1 #2;1 to class 4: 7
#I  Number of descendants of group #2;1 #3;1 #2;1 #1;1 to class 5: 6
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #2;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #3;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #4;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #5;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #6;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #2;1 #7;1 to class 5: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #3;1 to class 4: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #4;1 to class 4: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #5;1 to class 4: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #3;1 #6;1 to class 4: 0
#I  group restored from file is incapable
#I  Number of descendants of group #2;1 #4;1 to class 3: 0
#I  group restored from file is incapable
#I  Number of descendants of group #3;1 to class 2: 0

#
gap> PqQuitAll();
gap> STOP_TEST( "PqDescendantsTreeCoclassOne-9-i.tst", 1 );
