# Generated by tst/make_example_tests.g from examples/PqDescendantsTreeCoclassOne-16-i
gap> START_TEST( "PqDescendantsTreeCoclassOne-16-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "G", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> G := ElementaryAbelianGroup( 16 );
<pc group of size 16 with 4 generators>
gap> procId := PqStart( G );;
gap> PqDescendantsTreeCoclassOne( procId : TreeDepth := 15, 
>                                       CapableDescendants );;
#I  Number of descendants of group #1;1 to class 2: 1
#I  Number of descendants of group #1;1 #1;1 to class 3: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 to class 4: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 to class 5: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 to class 6: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 7: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 8: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 9: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 10: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 11: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 12: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 13: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 14: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 15: 1
#I  Number of descendants of group #2;1 to class 2: 1
#I  Number of descendants of group #1;1 #1;1 to class 3: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 to class 4: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 to class 5: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 to class 6: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 7: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 8: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 9: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 10: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 11: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 12: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 13: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 14: 1
#I  Number of descendants of group #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 #1;1 to class 15: 1

#
gap> PqQuitAll();
gap> STOP_TEST( "PqDescendantsTreeCoclassOne-16-i.tst", 1 );
