# Generated by tst/make_example_tests.g from examples/PqEpimorphism
gap> START_TEST( "PqEpimorphism.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "PqEpimorphism", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "phi" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup (2, "F");
<free group on the generators [ F1, F2 ]>
gap> procId := PqStart( F );
1
gap> phi := PqEpimorphism( procId : Prime := 5, ClassBound := 2 );
[ F1, F2 ] -> [ f1, f2 ]
gap> Image( phi );
<pc group of size 3125 with 5 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "PqEpimorphism.tst", 1 );
