# Generated by tst/make_example_tests.g from examples/PqPCover
gap> START_TEST( "PqPCover.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "PqPCover", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "procId1", "procId2", "procId3", "procId4", "G", "R", "H", "rels" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b"); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> procId1 := PqStart( F );
1
gap> PqPCover( procId1 : Prime := 2, ClassBound := 3 );
<pc group of size 262144 with 18 generators>
gap> # Now let's get a p-cover of a p-quotient of an fp group
gap> G := F / [a^4, b^4];
<fp group on the generators [ a, b ]>
gap> procId2 := PqStart( G );
2
gap> PqPCover( procId2 : Prime := 2, ClassBound := 3 );
<pc group of size 16384 with 14 generators>
gap> # Now let's get a p-cover of a different p-quotient of the same group
gap> PqPCover( procId2 : Prime := 2, ClassBound := 3, 
>               RedoPcp,
>               Exponent := 4 );
<pc group of size 8192 with 13 generators>
gap> # Now we'll get a p-cover of a p-quotient of another fp group
gap> # which we will redo using the `Relators' option
gap> R := [ a^25, Comm(Comm(b, a), a), b^5 ];
[ a^25, a^-1*b^-1*a*b*a^-1*b^-1*a^-1*b*a^2, b^5 ]
gap> H := F / R;
<fp group on the generators [ a, b ]>
gap> procId3 := PqStart( H );
3
gap> PqPCover( procId3 : Prime := 5, ClassBound := 5, Metabelian );
<pc group of size 48828125 with 11 generators>
gap> # Now we redo the previous example using the `Relators' option
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> rels := [ "a^25", "[b, a, a]", "b^5" ];
[ "a^25", "[b, a, a]", "b^5" ]
gap> procId4 := PqStart( F );
4
gap> PqPCover( procId4 : Prime := 5, ClassBound := 5, Metabelian, 
>               Relators := rels );
<pc group of size 48828125 with 11 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "PqPCover.tst", 1 );
