# Generated by tst/make_example_tests.g from examples/PqSupplementInnerAutomorphisms
gap> START_TEST( "PqSupplementInnerAutomorphisms.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "PqSupplementInnerAutomorphisms", PqStart )
gap> PqQuitAll();
gap> Perform( [ "Q", "procId", "des", "S", "A", "Inn" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> procId := PqStart( FreeGroup(2) );
1
gap> Q := Pq( procId : Prime := 3, ClassBound := 1 );
<pc group of size 9 with 2 generators>
gap> PqSetPQuotientToGroup( procId );;
gap> des := PqDescendants( procId : StepSize := 1 );
[ <pc group of size 27 with 3 generators>, 
  <pc group of size 27 with 3 generators>, 
  <pc group of size 27 with 3 generators> ]
gap> S := PqSupplementInnerAutomorphisms( des[3] );;
gap> A := AutomorphismGroup( des[3] );;
gap> Inn := InnerAutomorphismsAutomorphismGroup( A );;
gap> Size( ClosureGroup( Inn, S.glAutos ) ) = Size( A );
true

#
gap> PqQuitAll();
gap> STOP_TEST( "PqSupplementInnerAutomorphisms.tst", 1 );
