# Generated by tst/make_example_tests.g from examples/R2-5-x-i
gap> START_TEST( "R2-5-x-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 5, Exponent := 5);;
gap> PqPcPresentation(procId : ClassBound := 6, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^14
gap> PqSetupTablesForNextClass(procId);;
#I  Setup performed for class 7
gap> PqTails(procId, 0);;
gap> PqDoConsistencyChecks(procId, 0, 0);;
gap> PqSetOutputLevel(procId, 3);;
gap> PqDoExponentChecks(procId);;
#I  The quotient relation is  .28
#I  Generator 28 is trivial
#I  Collected power 5 of the following word: 1^1 
#I  The quotient relation is  .29
#I  Generator 29 is trivial
#I  Collected power 5 of the following word: 2^1 
#I  2 relations of class 1 collected
#I  The quotient relation is  .15 .16 .17^2 .18^3 .19^4 .20^3 .21^3 .22 .23 .24^4 .26^4 .27^2 .28 .29
#I  Generator 26 is redundant
#I  Collected power 5 of the following word: 1^1 2^1 
#I  1 relation of class 2 collected
#I  The quotient relation is  .15^3 .16^2 .17 .18^3 .22^4 .23^2 .24 .25^3 .26^4 .27^3 .28 .29^2
#I  Generator 25 is redundant
#I  Collected power 5 of the following word: 1^1 2^2 
#I  1 relation of class 3 collected
#I  The quotient relation is  .15 .17 .18^4 .22^4 .23^3 .24 .25 .26^4 .27^3 .28 .29^3
#I  Generator 24 is redundant
#I  Collected power 5 of the following word: 1^1 2^3 
#I  The quotient relation is  .15^2 .28
#I  Generator 15 is trivial
#I  Collected power 5 of the following word: 1^1 5^1 
#I  The quotient relation is  .22 .29
#I  Generator 22 is trivial
#I  Collected power 5 of the following word: 2^1 4^1 
#I  3 relations of class 4 collected
#I  The quotient relation is  .16^2 .17 .19 .20^3 .21^3 .23^4 .24^4 .25 .26^4 .27^2 .28 .29^4
#I  Generator 23 is redundant
#I  Collected power 5 of the following word: 1^1 2^4 
#I  The quotient relation is  .15^4 .16^4 .18 .20^4 .21^4 .22^2 .23 .24^4 .26^4 .27^2 .28 .29
#I  Generator 21 is redundant
#I  Collected power 5 of the following word: 1^1 2^1 4^1 
#I  2 relations of class 5 collected
#I  The quotient relation is  .15^4 .16^4 .17^3 .18^2 .19^4 .20^3 .21^3 .23^2 .24 .25^3 .26^4 .27^3 .28 .29^2
#I  Generator 19 is redundant
#I  Collected power 5 of the following word: 1^1 2^2 4^1 
#I  1 relation of class 6 collected
#I  The quotient relation is  .16^2 .17^3 .19^4 .20^2 .21^2 .23^3 .24 .25 .26^4 .27^3 .28 .29^3
#I  Collected power 5 of the following word: 1^1 2^3 4^1 
#I  1 relation of class 7 collected

#
gap> PqQuitAll();
gap> STOP_TEST( "R2-5-x-i.tst", 1 );
