# Generated by tst/make_example_tests.g from examples/R2-5-i
gap> START_TEST( "R2-5-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F", "procId", "class" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup("a", "b");
<free group on the generators [ a, b ]>
gap> procId := PqStart(F : Prime := 5, Exponent := 5);;
gap> PqPcPresentation(procId : ClassBound := 1, 
>                           OutputLevel := 1);;
#I  Lower exponent-5 central series for [grp]
#I  Group: [grp] to lower exponent-5 central class 1 has order 5^2
gap> PqSupplyAutomorphisms(procId, [ [[2,0],
>                                  [0,1]],
> 
>                                 [[4,1],
>                                  [4,0]] ]);;
gap> for class in [2 .. 13] do
>   PqNextClass(procId : QueueFactor := 20);
> od;
#I  Group: [grp] to lower exponent-5 central class 2 has order 5^3
#I  Group: [grp] to lower exponent-5 central class 3 has order 5^5
#I  Group: [grp] to lower exponent-5 central class 4 has order 5^8
#I  Group: [grp] to lower exponent-5 central class 5 has order 5^10
#I  Group: [grp] to lower exponent-5 central class 6 has order 5^14
#I  Group: [grp] to lower exponent-5 central class 7 has order 5^18
#I  Group: [grp] to lower exponent-5 central class 8 has order 5^22
#I  Group: [grp] to lower exponent-5 central class 9 has order 5^28
#I  Group: [grp] to lower exponent-5 central class 10 has order 5^31
#I  Group: [grp] to lower exponent-5 central class 11 has order 5^33
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^34
#I  Group completed. Lower exponent-5 central class = 12, Order = 5^34
#I  Group: [grp] to lower exponent-5 central class 12 has order 5^34
gap> PqSavePcPresentation(procId, ANUPQData.outfile);;

#
gap> PqQuitAll();
gap> STOP_TEST( "R2-5-i.tst", 1 );
