# Generated by tst/make_example_tests.g from examples/StandardPresentation
gap> START_TEST( "StandardPresentation.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );

# interactive form: PqExample( "StandardPresentation", PqStart )
gap> PqQuitAll();
gap> Perform( [ "F", "a", "b", "procId1", "procId2", "procId3", "G", "S", "Spc", "H", "F4", "c", "d", "G4", "K" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F := FreeGroup( "a", "b" ); a := F.1; b := F.2;
<free group on the generators [ a, b ]>
a
b
gap> G := F / [a^25, Comm(Comm(b, a), a), b^5];
<fp group on the generators [ a, b ]>
gap> procId1 := PqStart( G );
1
gap> S := StandardPresentation( procId1 : Prime := 5, ClassBound := 10 );
<fp group on the generators [ f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, 
  f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26 ]>
gap> IsPcGroup( S );
false
gap> # if we need to compute with S we should convert it to a pc group
gap> Spc := PcGroupFpGroup( S );
<pc group of size 1490116119384765625 with 26 generators>
gap> H := F / [ a^625, Comm(Comm(Comm(Comm(b, a), a), a), a)/Comm(b, a)^5,
>            Comm(Comm(b, a), b), b^625 ];
<fp group on the generators [ a, b ]>
gap> procId2 := PqStart( H );
2
gap> StandardPresentation( procId2 : Prime := 5, ClassBound := 15, 
>                           Metabelian );
<fp group on the generators [ f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, 
  f12, f13, f14, f15, f16, f17, f18, f19, f20 ]>
gap> F4 := FreeGroup( "a", "b", "c", "d" );
<free group on the generators [ a, b, c, d ]>
gap> a := F4.1; b := F4.2; c := F4.3; d := F4.4;
a
b
c
d
gap> G4 := F4 / [ b^4, b^2 / Comm(Comm (b, a), a), d^16,
>              a^16 / (c * d), b^8 / (d * c^4) ];
<fp group on the generators [ a, b, c, d ]>
gap> procId3 := PqStart( G4 );
3
gap> K := Pq( procId3 : Prime := 2, ClassBound := 1 );
<pc group of size 4 with 2 generators>
gap> StandardPresentation( procId3 : pQuotient := K, ClassBound := 14 );
<fp group with 53 generators>

#
gap> PqQuitAll();
gap> STOP_TEST( "StandardPresentation.tst", 1 );
