# Generated by tst/make_example_tests.g from examples/StandardPresentation-i
gap> START_TEST( "StandardPresentation-i.tst" );
gap> SetInfoLevel( InfoANUPQ, 1 );
gap> PqQuitAll();
gap> Perform( [ "F4", "a", "b", "c", "d", "G4", "procId", "lev" ],
>      function( v ) if IsBoundGlobal( v ) then UnbindGlobal( v ); fi; end );
gap> F4 := FreeGroup( "a", "b", "c", "d" );
<free group on the generators [ a, b, c, d ]>
gap> a := F4.1; b := F4.2; c := F4.3; d := F4.4;
a
b
c
d
gap> G4 := F4 / [ b^4, b^2 / Comm(Comm (b, a), a), d^16,
>              a^16 / (c * d), b^8 / (d * c^4) ];
<fp group on the generators [ a, b, c, d ]>
gap> procId := PqStart( G4 );;
gap> Pq( procId : Prime := 2, ClassBound := 1 );
<pc group of size 4 with 2 generators>
gap> # the computed p-quotient is ``remembered'' and supplies the
gap> # `pQuotient' option to `StandardPresentation' ...
gap> StandardPresentation( procId : ClassBound := 14 );
<fp group with 53 generators>
gap> # `StandardPresentation' and `EpimorphismStandardPresentation'
gap> # behave like attributes, so no computation is done when
gap> # either is called again for the same process ...
gap> lev := InfoLevel(InfoANUPQ);
1
gap> SetInfoLevel(InfoANUPQ, 2);; # To see computation time
gap> EpimorphismStandardPresentation( procId : ClassBound := 14 );
[ a, b, c, d ] -> [ f1, f2, f13*f20*f28, f20*f24*f33 ]
gap> # No timing data was Info-ed since no computation was done
gap> SetInfoLevel(InfoANUPQ, lev);; # Restore previous InfoANUPQ level

#
gap> PqQuitAll();
gap> STOP_TEST( "StandardPresentation-i.tst", 1 );
