#!/bin/sh
#############################################################################
##
#W  mkdiff         Differences of the manual examples          Volkmar Felsch
##
#H  $Id$
##
#Y  Copyright (C) 2002, Lehrstuhl D fuer Mathematik, RWTH Aachen, Germany
##
##  mkdiff.sh [-c] [file1 file2 ...]
##
##  This is the 'mkdiff' version for package documentations.
##
##  For each file name 'file', say, in the given list of file names compare
##  the manual file '../file.tex' with the test file 'file.tst' and write all
##  differences to a file 'diffs'.
##
##  If '-c' is specified use the context output format of the 'diff' command.
##
##  If no file names are specified handle all '.tst' files in the current
##  directory.
##

#############################################################################
##
##  Define the local call of the proper test function.
##
mkdiff="../../../../doc/test/mkdiff.sh"


#############################################################################
##
##  Run the test for eacxh of the documentation files.
##
$mkdiff $*

